### ISSUE TITLE
Antlr4Compile target failed to detect Java on OS X

### ISSUE THREAD

**Issue by lextm** [tunnelvisionlabs/antlr4cs#100]
On OS X and Xamarin Studio, with Oracle Java installed, but still get this error message.
```	
        Target Antlr4Compile:
:  warning AC1000: Unknown build error: Could not locate a Java installation.
		Previous error was converted to a warning as the task was called with ContinueOnError=true.
	Task "Antlr4ClassGenerationTask" execution -- FAILED
```

**Comment by sharwell** [comment]
Hi @lextm,

Sorry things aren't working for you the way you expected. The ongoing work in #94 should (eventually) resolve your situation as well. Would you like to take a look at that discussion and let me know what you think?

Thanks!
