### ISSUE TITLE
Nice to have enumerable for tokens

### ISSUE THREAD

**Issue by hungdluit** [tunnelvisionlabs/antlr4cs#101]
Hi,

I know it just a personal problem. To me, it is very terrible to use a string comparison to find out a token in lexer. I feel uncomfortable to make the grammar after implementing csharp to work with antlr lexer.

If I missed somethings that you already have this one. Please, introduce it to me.

Thanks for understanding,

**Comment by sharwell** [comment]
Hi @hungdluit,

Can you show an example of what is causing problems? I don't think I understood your request.

Thank you! :smile:

**Comment by hungdluit** [comment]
I'm writing a java parser by anltr4 in vs2013. An using grammar in https://github.com/hungdluit/grammars-v4/blob/master/java/Java.g4.

The problem is when I try to use vistor to determine modifier for a class/interface.

       if(context.classOrInterfaceModifier() != null)
              {
                Transpiler.Compilers.Java.AbstractJavaParser.ClassOrInterfaceModifierContext sub = context.classOrInterfaceModifier(0);
                if(sub.ChildCount != 0)
                {
                    TerminalNodeImpl node = sub.children[0] as TerminalNodeImpl;
                    if(node == null
                        || node.Symbol == null)
                    {
                        throw new InvalidOperationException("Cannot find object's modifier");
                    }
                    if(node.Symbol.Type == 35)
                     {
                          // public modifier
                     }
                }
            }

            throw new InvalidOperationException("Cannot find object's modifier"); 

I would like to see something likes
  if(node.Symbol.Type == SymbolTypes.Public)
     {
          // public modifier
      }
Thank you :)

**Comment by sharwell** [comment]
I believe the constant you are looking for is `JavaLexer.PUBLIC`, which is created due to this lexer rule:

https://github.com/hungdluit/grammars-v4/blob/d4afc21f7c9687d84e3dc1847f83012d986f44e7/java/Java.g4#L646

**Comment by hungdluit** [comment]
looks great. Thank you :dancer:

**Comment by sharwell** [comment]
Happy to help :+1:
