### ISSUE TITLE
Java installation via environment variable not working

### ISSUE THREAD

**Issue by JohnWashburn** [tunnelvisionlabs/antlr4cs#102]
The ANTLR4 C# targets do not read the environment variable: JAVA_HOME 
This is a resurrection of https://github.com/antlr/antlr4/issues/520 but is targeted to the build I am using: Antlr4 4.3.0.

See corrected steps to reproduce in the comment below.

My environment is Windows 7 x64 with VS2012.

Steps to reproduce:
1) install the SE JRE 1.8 from http://www.oracle.com/technetwork/java/javase/downloads/jre8-downloads-2133155.html
2) This will install in to C:\Program Files\Java\jre1.8.0_40
3) copy C:\Program Files\Java\jre1.8.0_40 to c:\jre8
4) set your environment variable, JAVA_HOME to c:\jre8
4a) Start menu -> Computer -> right click -> Properties-> advanced system settings -> environment variables -> System Variables -> New -> Variable name = JAVA_HOME Variable Value = C:\jre8
5a) Install the ANTLR4 language support for VS2012 found at: https://visualstudiogallery.msdn.microsoft.com/25b991db-befd-441b-b23b-bb5f8d07ee9f
5b) Install the ANTLR4 language support for VS2012 using Tools-> Extensions and Updates. Search by ANTLR4
5c) Restart VS2012
6) Create an class library project named HelloGrammar
6a) delete the Class1 template created for you
6b) add a new Visual C# item of type ANTLR named HelloGrammar.g4
6c) Using Manage nuget packages add the nuget package, Antlr4 (C# target for 2010+ projectc) from Nuget.org.  this will also install the 4.3.0 ANTLR runtime
6d) verify the project build by rebuilding the solution  
7) Create a second project named GrammarClient which is a Windows Form applicaiton.
7a) add a reference to the HelloGrammar project
7b) add existing items: ../helloGrammar/obj/debug/HelloGrammarBaseListener.cs and HelloGrammarBaseVisitor.cs as *LINKED* references.
7c) Using Manage Nuget Packages add the nuget package, 4.3.0 ANTLR runtime
8) Insure the solution builds both projects without error by rebuilding the whole solution
9) Renamed the directory *C:\Program Files\Java\jre1.8.0_40* to *C:\Program Files\Java\JWW.jre1.8.0_40*
10) Rebuild the solution: Hello Grammar.  You will now get: 
  Unknown build error: The system cannot find the file specified *~\HelloGrammar\packages\Antlr4.4.3.0\build\Antlr4.targets*.
11) Renamed the directory *C:\Program Files\Java\JWW.jre1.8.0_40* back to *C:\Program Files\Java\jre1.8.0_40*
10) Rebuild the solution: Hello Grammar.  All is good again.

The first problem is the error message emitted is worse the useless because it actively deceives you.  The file, *Antlr4.targets*, exists exactly where the error message tells you it does not exist.

I inferred from the method named JavaHome in the file Antlr4ClassGenerationTaskInternal.cs that this 
chunk of code:

        private string JavaHome
        {
            get
            {
                string javaHome;
                if (TryGetJavaHome(RegistryView.Default, JavaVendor, JavaInstallation, out javaHome))
                    return javaHome;

                if (TryGetJavaHome(RegistryView.Registry64, JavaVendor, JavaInstallation, out javaHome))
                    return javaHome;

                if (TryGetJavaHome(RegistryView.Registry32, JavaVendor, JavaInstallation, out javaHome))
                    return javaHome;

                if (Directory.Exists(Environment.GetEnvironmentVariable("JAVA_HOME")))
                    return Environment.GetEnvironmentVariable("JAVA_HOME");

                throw new NotSupportedException("Could not locate a Java installation.");
            }
        }

Would use C:\Jre8 as the location of the JRE, but this is not the case as the above steps prove.  

For the misleading error message, I believe this inarticulate message derives from line 249 in Antlr4ClassGenerationTask.cs and not reporting all of the exception information available.  I think line 249 should read:

    ProcessBuildMessage(new BuildMessage(exception.ToString()));

So the *whole* exception structure (message, stack trace and most importantly, the inner exception(s)) is presented to the user.

But the main point on this issue is JAVA_HOME is not read even though *%JAVA_HOME%\bin\java.exe* is a perfectly legal path to a properly working JRE.  The ANTLR C# language support though does not recognize the environment variable, JAVA_HOME, the same way as a registry key named: JavaHome.

**Comment by JohnWashburn** [comment]
If this is indeed a problem in JavaHome,  may I ask that the error message be improved?  

Having been on the receiving end of error message such as the one above (a single phrase use for several failure modes (JavaHome proper) and several phrases for the same failure mode as done in ProcessExceptionAsBuildMessage(Exception exception)), your life will be easier if you tell the developer (aka us) more precisely what went of the rails where while searching for what.

        private string JavaHome
        {
            get
            {
              string javaHome;
              var searchNotes = new StringBuilder(@"Could not locate a Java installation.\n");

              searchNotes.AppendFormat("  Searched: TryGetJavaHome(RegistryView.Default={0}, JavaVendor={1}, JavaInstallation={2}, out javaHome)\n"
                                      , RegistryView.Default, JavaVendor, JavaInstallation);
                if (TryGetJavaHome(RegistryView.Default, JavaVendor, JavaInstallation, out javaHome))
                    return javaHome;

                searchNotes.AppendFormat("  Searched: TryGetJavaHome(RegistryView.Default={0}, JavaVendor={1}, JavaInstallation={2}, out javaHome)\n"
                                        , RegistryView.Registry64, JavaVendor, JavaInstallation);
                if (TryGetJavaHome(RegistryView.Registry64, JavaVendor, JavaInstallation, out javaHome))
                    return javaHome;

                searchNotes.AppendFormat("  Searched: TryGetJavaHome(RegistryView.Default={0}, JavaVendor={1}, JavaInstallation={2}, out javaHome)\n"
                                        , RegistryView.Registry32, JavaVendor, JavaInstallation);
                if (TryGetJavaHome(RegistryView.Registry32, JavaVendor, JavaInstallation, out javaHome))
                    return javaHome;

                searchNotes.AppendLine("  Searched: Directory.Exists(Environment.GetEnvironmentVariable(\"JAVA_HOME\"))");
              searchNotes.AppendFormat("            Directory.Exists(Environment.GetEnvironmentVariable({0})) = {1}\n"
                                        , Environment.GetEnvironmentVariable("JAVA_HOME") ?? "<Null>"
                                        , (null != Environment.GetEnvironmentVariable("JAVA_HOME")) ? Directory.Exists(Environment.GetEnvironmentVariable("JAVA_HOME")).ToString() : "Unknown");
                if (Directory.Exists(Environment.GetEnvironmentVariable("JAVA_HOME")))
                    return Environment.GetEnvironmentVariable("JAVA_HOME");

                throw new NotSupportedException(searchNotes.ToString());
            }
        }

The Java Home on the other side of the #IF would have a similar  error message build from a StringBuillder.  This way the message that eventually bubbles up to the automated TeamCity build log would inform me when I read the log *the next morning* where within the TeamCity agent the ANTLR runtime was looking for and not finding the JRE which TeamCity copied into *C:\build\bin\..\jre* and noted that location within the JAVA_HOME environment variable.  

Maybe TeamCity is not copying the JRE, Maybe TC is not setting the JAVA_HOME, maybe antlr.runtime.dll is not reading JAVA_HOME.  I took me some time but I narrowed the root cause down to the third option.

**Comment by JohnWashburn** [comment]
upon further reflection my steps to reproduce are actually to reproduce a corrupted install because the registry entry JavaHome exists, but points to the incorrect directory when the directory is renamed to *C:\Program Files\Java\JWW.jre1.8.0_40*

If the setup steps are changed as follows:
1) install the SE JRE 1.8 
1a) create a directory named C:\temp
1b) Copy the JRE installer from http://www.oracle.com/technetwork/java/javase/downloads/jre8-downloads-2133155.html to c:\temp
1c) CD to C:\temp
1d) Install the JRE using the installer found in c:\temp
2) This will install in to C:\Program Files\Java\jre1.8.0_40
3) copy C:\Program Files\Java\jre1.8.0_40 to c:\jre8
4) set your environment variable, JAVA_HOME to c:\temp\..\jre8
4a) Start menu -> Computer -> right click -> Properties-> advanced system settings -> environment variables -> System Variables -> New -> Variable name = JAVA_HOME Variable Value = C:\temp\..\jre8

Steps 5-8 are as above

9) Uninstall the JRE 1.8
9a) Start Panel -> Control Panel->uninstall a program
9b) Reboot computer
10) open VS2012
11) Rebuild the solution: Hello Grammar. You will now get:
*Unknown build error: Could not locate a Java installation. ~\HelloGrammar\packages\Antlr4.4.3.0\build\Antlr4.targets*
12) Re-Install the JRE
12a) cd C:\temp\
12b) Install the JRE using the installer found in c:\temp
13) Rebuild the solution: Hello Grammar. All is good again.

Uninstalling the JRE and setting the environment variable JAVA_HOME to the simpler: c:\Jre8 still gives you the same error from the property, JavaHome,
*Unknown build error: Could not locate a Java installation. ~\HelloGrammar\packages\Antlr4.4.3.0\build\Antlr4.targets*

**Comment by JohnWashburn** [comment]
JAVA_HOME = C:\temp\..\jre8
or 
JAVA_HOME = C:\jre8

**Comment by sharwell** [comment]
I believe the ongoing work in #94 will address this issue as well. I'd be interested in your feedback on that. :smile:

**Comment by JohnWashburn** [comment]
Dear Mr. Harwell:

 

Yes, #94 <https://github.com/tunnelvisionlabs/antlr4cs/pull/94>  would, I guess, maybe, solve the problems of #100 <https://github.com/tunnelvisionlabs/antlr4cs/issues/100>  and #102 <https://github.com/tunnelvisionlabs/antlr4cs/issues/102> , but why are issues #100 <https://github.com/tunnelvisionlabs/antlr4cs/issues/100>  and #102 <https://github.com/tunnelvisionlabs/antlr4cs/issues/102> , even linked at all to #94 <https://github.com/tunnelvisionlabs/antlr4cs/pull/94> ?  Issue #94 is not the same problem as #100 and #102.  I will give you though that #100 and #102 are the same problem on differing operating systems.

 

Both #100 <https://github.com/tunnelvisionlabs/antlr4cs/issues/100>  and #102 <https://github.com/tunnelvisionlabs/antlr4cs/issues/102>  assume there is a properly installed JRE on the build machine at the location referenced by the JAVA_HOME environment variable, but the ANTLR runtime system does not read the environment variable as documented (or as the code in the JavaHome property would lead one to believe).

  

Issue #94 <https://github.com/tunnelvisionlabs/antlr4cs/pull/94>  assumes there is no JRE installed anywhere on the build machine and thus a fall back JRE is needed.  

 

These are not the same use cases.

 

I am now tempted to fire up my ubuntu / mono environment and see if the ANTLR C# targets don’t read the JAVA_HOME variable properly by on a Linux system in the same way as JAVA_HOME is not read properly on a Mac OSx system and not read properly on Windows 7 build machine.

 

Don’t take this as a criticism of the C# targets.  I am delighted with the two grammars I have created.  I am just bummed I cannot include ANTLR grammars into the company’s TeamCity build process yet because the ANTLR runtimes cannot find the installed JRE based on the JAVA_HOME environment variable.  This is an odd gap in functionality for a system that depends on a JRE.

**Comment by JohnWashburn** [comment]
I issued the following command on my local machine:

    "C:\temp\..\jre8\bin\java.exe" -cp "C:\Users\jwashbur\Documents\My Git Repos\GeneralProgramming\HelloGrammar\packages\Antlr4.4.3.0\build\..\tools\antlr4-csharp-4.3-complete.jar" org.antlr.v4.CSharpTool -o obj\Debug\ -listener -visitor -Dlanguage=CSharp_v3_5 -package HelloGrammar "C:\Users\jwashbur\Documents\My Git Repos\GeneralProgramming\HelloGrammar\HelloGrammar\HelloGrammar.g4"

I mutated the result from the Output window of a build above when the JRE was installed.  I alter the result from 
    "C:\Program Files\Java\jre1.8.0_40\bin\java.exe" 
to 
    "C:\temp\..\jre8\bin\java.exe" 
in order to simulating the result if the JAVA_HOME environment variable had been read properly by the C# ANTLR runtime

**Comment by JohnWashburn** [comment]
I see the source of my confusion now.  

Neither Commit 84b936a70a058cb3401acbc26252e5b83d261328 (4.3.0) nor commit/878739f6e4dd1304f8e45865c4f523522f0df590 (v4.4.1-alpha001) has the code I referenced for JavaHome which is from the latest commit (8845ad6515c8d3cbb52d819a78e687e6010076eb). 

DOH!!! 

What I will do for the interim is create a local patch on my local system which incorporates the code in JavaHome which reads the environment variable, JAVA_HOME.  I can then give the local nuget package a version number of 4.3.2 and store it in my local package source.  I can then wait for the resolution of #100, #94, and #102 to be included in the next release of antlr4cs (e.g. 4.4.x).

Thank you for your indulgence on my confusion with the GIT commits and which code was in which release.  The face palm left a mark.
