### ISSUE TITLE
Visual Studio 2013 and Antlr C# Import problem

### ISSUE THREAD

**Issue by fireboy0526** [tunnelvisionlabs/antlr4cs#105]
Hello there,

I've been using antlr with Visual Studio and so I've import the Antlr package from Nuget. However, with Antlr4.3, it is causing that error with importing lexer and parser files, which can be found on antlr/antlr4#670.

Is it possible to request an update of the Antlr version on Nuget please.

Thank you very much.

This is the error message that I'm getting (please note that this isn't all the error message)
"Error	3	Unknown build error: Exception in thread "main" java.util.NoSuchElementException: token index 808 out of range 0..93	J2Net
"

**Comment by sharwell** [comment]
Hi @fireboy0526,

I don't remember if the 4.4.1 prerelease package on NuGet included the fix for this, but either way I hope to release an updated package very soon. I'll make sure it includes the fix for this.

**Comment by fireboy0526** [comment]
Hello @sharwell 

Thank you very much for your reply. I do look forward to see the update.

From what I've been reading from the original Antlr repository, it seems that version 4.5.1 have the fix to this problem. Once again, thank you for your hard work.
