### ISSUE TITLE
cannot run build.ps1 without Visual Studio 2008 installed

### ISSUE THREAD

**Issue by ViceIce** [tunnelvisionlabs/antlr4cs#109]
The .Net Compact Framework parts can only be build with VS2008.

We should think about to drop support with next major release and add some conditionals to build scripts till end of support.

**Comment by sharwell** [comment]
So on the current machine I actually can't test this because Visual Studio 2013 isn't installed, and that build runs before the .NET 3.5 CF build in **build.ps1**. :expressionless: Of course I can rearrange things to get it moving; I'll do so this evening. I'm really hoping the only thing needed to build the project you refer to is the [https://www.microsoft.com/en-us/download/details.aspx?id=65](.NET Compact Framework 3.5 Redistributable) package. Either way it makes sense to include a build flag to disable this build.

**Comment by ViceIce** [comment]
@sharwell Link is defect.

**Comment by ViceIce** [comment]
Nope, not enough:
```
antlr4cs\Runtime\CSharp\Antlr4.Runtime\Antlr4.Runtime.net35-cf.csproj(287,3): error MSB4019: Das importierte Projekt "C:\Windows\Microsoft.NET\Framework\v3.5\Microsoft.CompactFramework.CSharp.targets" wurde nicht gefunden. Vergewissern Sie sich, dass der Pfad in der <Import>-Deklaration korrekt und die Datei auf dem Datenträger vorhanden ist.
```

Sorry, but german system.

**Comment by sharwell** [comment]
This is probably still incomplete, but hopefully it is a start.

### Prerequisites

* Visual Studio 2012, 2013, or 2015
* [.NET Compact Framework 3.5 Redistributable](https://www.microsoft.com/en-us/download/details.aspx?id=65)
* [Power Toys for .NET Compact Framework 3.5](https://www.microsoft.com/en-us/download/details.aspx?id=13442)
* JDK or JRE from Java 6

### Environment

| Environment Variable | Value |
| --- | --- |
| `M2_HOME` | Maven home |

### Special notes

* If you do not have Visual Studio 2013 installed, you need to pass the `-VisualStudioVersion` argument to the build script. The argument value is set as follows.
  * If you have Visual Studio 2015 installed, you need to pass `-VisualStudioVersion 14.0`.
  * If you have Visual Studio 2012 installed, you need to pass `-VisualStudioVersion 11.0`.

**Comment by ViceIce** [comment]
:+1: The PowerToys were missing on my machine.

But it does not find my "jre1.8.0_45" (x64).

**Comment by sharwell** [comment]
Try setting `JAVA_HOME`. I set that environment variable in the same script that sets `M2_HOME`; I didn't include it in the table above because I wasn't sure it was needed.

**Comment by ViceIce** [comment]
`JAVA_HOME` is set to `C:\Program Files\Java\jdk1.8.0_25`

**Comment by sharwell** [comment]
Did you mean `45` (instead of `25`)?

**Comment by ViceIce** [comment]
Ah, sorry i see the error. Yesterday I updated may jdk an does not restart my shell. :flushed:

**Comment by ViceIce** [comment]
We should add your build description to a reame file.

**Comment by sharwell** [comment]
Once it's updated to include any changes you had to make to it, I certainly agree!
