### ISSUE TITLE
Lexer & parser tokens' values don't match in v4.3 (using modes, FWIW)?

### ISSUE THREAD

**Issue by taliano** [tunnelvisionlabs/antlr4cs#116]
I hope I diagnosed the issue correctly: the following lexer and parser rules produce different token-values in the generated `SimplestLexer` and `SimplestParser` classes: in the `SimplestLexer` class the `BODY` token is 6, while in the `SimplestParser` class it's 3

The input test string:

	var test = "cmd   some -> \"string\" thing...    \r\n" +
			   "if";

Parser:

	parser grammar SimplestParser;

	root: (if|cmd)* EOF;
	if	: IF;
	cmd	: WORD BODY?;

Lexer:

	lexer grammar SimplestLexer;

	IF	: 'if';
	WORD: [-_0-9a-zA-Z]+ -> mode(IN_CMD);
	WS	: [ \t\r\n] -> skip;

	mode IN_CMD;
		GAP	: [ \t]+ -> skip, mode(IN_BODY);
		EOC	: '\r'? '\n' -> skip, mode(DEFAULT_MODE);

	mode IN_BODY;	
		BODY: ~[\r\n]+;
		EOB	: '\r'? '\n' -> skip, mode(DEFAULT_MODE);

Beginning of the SimplestParser class:

	[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.3")]
	[System.CLSCompliant(false)]
	public partial class SimplestParser : Parser {
		public const int
			IF=1, WORD=2, BODY=3;
	/*
		rest of the class ...
	*/	
	}

Beginning of the SimplestLexer class:

	[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.3")]
	[System.CLSCompliant(false)]
	public partial class SimplestLexer : Lexer {
		public const int
			IF=1, WORD=2, WS=3, GAP=4, EOC=5, BODY=6, EOB=7;
	/*
		rest of the class ...
	*/	
	}

Beginning of the `cmd()` parser's method:

	202	[RuleVersion(0)]
	203	public CmdContext cmd() {
	204		CmdContext _localctx = new CmdContext(_ctx, State);
	205		EnterRule(_localctx, 4, RULE_cmd);
	206		int _la;
	207		try {
	208			EnterOuterAlt(_localctx, 1);
	209			{
	210			State = 17; Match(WORD);
	211			State = 19;
	212			_la = _input.La(1);
	213			if (_la==BODY) { // apparently this is the problem: _la == 6 and BODY == 3
	214				{
	215				State = 18; Match(BODY);
	216				}
	217			}
	218
	219			}
	220		}
		/*
			rest of the method ...
		*/
	230	}

When exiting the `cmd()` method (see line number 213), the next `_errHandler.Sync(this);` calls to the `MyDerivationOf_BaseErrorListener.SyntaxError()` with the following error message:

	extraneous input 'some -> "string" thing...    ' expecting {<EOF>, IF, WORD}

I'm using (currently) Visual Studio 2013.

**Comment by sharwell** [comment]
Your parser grammar is missing a `tokenVocab` option. Without it, your parser and lexer are treated as independent grammars, so there is no attempt to use the same values for tokens.

```antlr
options {
  tokenVocab = SimplestLexer;
}
```

:memo: You actually received a warning during the build telling you that there is no lexer rule matching the `IF`, `WORD`, and `BODY` tokens used in the parser. When you see this warning, you should fix it or you'll get the runtime problem you described with this issue. :+1:
