### ISSUE TITLE
Do your team have any plan to upgrade current version (4.5) into .NET 4.6?

### ISSUE THREAD

**Issue by thangchung** [tunnelvisionlabs/antlr4cs#117]
I have worked on a parser for my project in .NET 4.6, I searched around internet and found out Antlr4cs is a good parser for my requirements, but I recognized that Antlr4cs only work on .NET 4.5 target. Do your team have any plan to upgrade to .NET 4.6 target?

**Comment by sharwell** [comment]
Hi @thangchung,

Thanks for reporting this. I didn't realize the recent release of .NET 4.6 broke this functionality. Support will be implemented by treating .NET 4.6 the same way as .NET 4.5 code [by updating this check](https://github.com/tunnelvisionlabs/antlr4cs/blob/b47473a79bbd31547d5e99eb728f54e6026ed6b9/runtime/CSharp/Antlr4BuildTasks/Antlr4ClassGenerationTaskInternal.cs#L304-L305).

**Comment by Tiliavir** [comment]
Is there going to be a beta release on nuget soon? Similar to the 4.5.0-alpha002?
