### ISSUE TITLE
AppVeyor reporting success even though build fails

### ISSUE THREAD

**Issue by afscrome** [tunnelvisionlabs/antlr4cs#121]
The build https://ci.appveyor.com/project/sharwell/antlr4cs/build/1.0.20 shows as successful, however if you scroll to the bottom, you can see there is a build failure

```
.NET 3.5 Compact Framework Build failed, aborting!
```

You may also wish to switch to the newer AppVeyor image - builds start nearly instantly, and you no longer need the `set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%` hack to use the newer msbuild.  See http://www.appveyor.com/blog/2015/06/23/new-oss-build-environment-and-xamarin-support for more details.

**Comment by sharwell** [comment]
> You may also wish to switch to the newer AppVeyor image - builds start nearly instantly

I'm on an AppVeyor Pro account, so the builds are even faster. :smile:

**Comment by afscrome** [comment]
Fair enough.  When I submitted my pull request, it took a couple of minutes before the build starts - I may have just hit a bad time.
