### ISSUE TITLE
Build Tools Nuget 3 Compatibility

### ISSUE THREAD

**Issue by afscrome** [tunnelvisionlabs/antlr4cs#124]
Currently the build tool packages uses the approach described at https://docs.nuget.org/create/creating-and-publishing-a-package#import-msbuild-targets-and-props-files-into-project to import the msbuild targets & props files into the target solution.   This approach however has been deprecated in NuGet 3 and so the build tools fail to register in a modern PCL project - http://docs.nuget.org/create/uwp-create#msbuild-targets-and-props-files-in-packages . 

For #120, we can get away without fixing this issue because the main Antlr4 project contains projects which restore the build tools using older nuget system, so the newer project works using the content restored for the older projects.

I've had a quick play getting this to work, but was not able to.  Will need to do some more investigation.

**Comment by sharwell** [comment]
@afscrome Can you check out **4.5.3.1-beta001** and let me know if any changes are still needed?

**Comment by afscrome** [comment]
LGTM from the nuget 3 side.

**Comment by sharwell** [comment]
@afscrome Thanks for following up, and sorry it took me so long to clean this up. :smile:
