### ISSUE TITLE
NuGet Package for .NET 4.6

### ISSUE THREAD

**Issue by Tiliavir** [tunnelvisionlabs/antlr4cs#126]
Hi there,

I saw in the commit log that there is a fix to support .NET 4.6. I had to update my project to 4.6 recently and had therefore to create a custom build of ANTLR4CS - it worked perfectly for me.
But is there going to be a prerelease on NuGet soon, so that I can commit my changes to our Repo?

Thanks in advance,
Markus

**Comment by sharwell** [comment]
I'll try to get one out tomorrow. Feel free to make a comment here tomorrow to remind me that I said this. :D

**Comment by sharwell** [comment]
Published today as [v4.5-alpha003](https://github.com/tunnelvisionlabs/antlr4cs/releases/tag/v4.5-alpha003).

**Comment by Tiliavir** [comment]
Thank you very much! That is working just perfectly! I didn't expect it that fast :+1:
