### ISSUE TITLE
Disable CS3021 compiler warning

### ISSUE THREAD

**Issue by sparticus1701** [tunnelvisionlabs/antlr4cs#133]
I am utilizing Antlr4 via Sam Harwell's Nuget package (v4.5.0-alpha003).  So far it is working well, but my compiler is giving me multiple warnings "Warning CS3021 '<classname>' does not need a CLSCompliant attribute because the assembly does not have a CLSCompliant attribute".

I would prefer not to receive this warning, but the code files are auto-generated.  I see that the generated files are disabling a few other warnings.  Is there a way for me to get this warning disabled?  I am using VS2015.

**Comment by GeorgDangl** [comment]
You can include directives in your source code to include certain warnings. ANTLR does this for a few warnings by default, but you can include the following code in your grammar to add CS3021 to the list of warnings to ignore:

    @header {
    #pragma warning disable 3021
    }

The line `#pragma warning disable 3021` will be placed at the top of the generated class and disable the automatic compiler warning for that file.

**Comment by sharwell** [comment]
You need to include the following in your **AssemblyInfo.cs** file:

```csharp
[assembly: CLSCompliant(false)]
```

This line explicitly states what is already the default value. All assemblies should include this line so warning CS3021 never appears.
