### ISSUE TITLE
.G4 File Encoding

### ISSUE THREAD

**Issue by Swkgram** [tunnelvisionlabs/antlr4cs#135]
Hello !  
I'm a CS student at Aalborg University. 
My group and I are creating our own compiler and language this year. We've decided to try out Antlr4.
When we tried to follow your guide we ran into a problem - specifically Step 7 in the: "Without using the ANTLR Language Support extension" section.
The language encoding  **Unicode (UTF-8 without signature) - Codepage 65001** results in errors:  
![image](https://cloud.githubusercontent.com/assets/9000666/13984542/26d5d086-f0f7-11e5-9e8a-01a146cb9ce7.png)
Our group found out that we should use **Western European (Windows) - Codepage 1252** encoding instead.

**Software:**
Windows 10  and Windows 10 Pro (English language)
Microsoft Visual Studio 2015 - Community Edition. (English language)
**Target Framework:**
.NET 4.5
**Antlr Version:**
4.3.0

Whether this problem is Windows 10 or VS2015 specific - or simply that the encoding is no longer supported by Antlr4, we do not know.

Kind regards Sebastian

**Comment by sharwell** [comment]
This is a bug in the code generator. It is supposed to support UTF-8 (with or without signature).
