### ISSUE TITLE
Not intuitive work with ErrorListener in parser or lexer

### ISSUE THREAD

**Issue by KvanTTT** [tunnelvisionlabs/antlr4cs#156]
The following lines do nothing:

``` C#
antlr4Parser.ErrorListeners.Clear();
antlr4Parser.ErrorListeners.Add(errorListener);
```

We should use this instead:

``` C#
antlr4Parser.RemoveErrorListeners();
antlr4Parser.AddErrorListener(errorListener);
```

Maybe it's better to make member `ErrorListeners` private or readonly?

**Comment by sharwell** [comment]
Definitely confusing. To avoid breaking changes in the API, I opted for commenting this.
