### ISSUE TITLE
syntax error: mismatched character '\r' expecting ']' while lexer rule contains ấ

### ISSUE THREAD

**Issue by u8621011** [tunnelvisionlabs/antlr4cs#162]
this lexer rule makes this error:
 
```
VOWELS_A_WITH_TONE : [ấầẩẫậ]+ ;
```

seems that's unicode problem?

Environment : visual studio 2015 save with,  utf-8 without signature, options.

**Comment by YangFan789** [comment]
Use \u escape character

**Comment by sharwell** [comment]
This looks like a duplicate of #135.

**Comment by juergenr** [comment]
Hi Sharwell,
I really like this great library - but I'm also suffering from the defect unicode (utf-8) support.
Maybe I have to switch to some other parser - but It's really difficult to find something comparable ;-)
But nevertheless thanks for your work!

**Comment by juergenr** [comment]
Hi Sharwell,
I really like this great library - but I'm also suffering from the defect unicode (utf-8) support.
Maybe I have to switch to some other parser - but It's really difficult to find something comparable ;-)
But nevertheless thanks for your great work!
