### ISSUE TITLE
How to get the AST of a C code in C#?

### ISSUE THREAD

**Issue by ionuttamas** [tunnelvisionlabs/antlr4cs#165]
Hello,

I just want to be able to get the AST of a C program in my C# application.
I've taken the ANTLR specification from [here](https://github.com/antlr/grammars-v4/blob/master/c/C.g4) and I want to know how can I get the AST of a C code using this file. 

Could anyone point me to the right track here?

PS: I have no idea on how to use that .g4 file also.

**Comment by sharwell** [comment]
The steps in the [project readme](https://github.com/tunnelvisionlabs/antlr4cs#readme) should provide information on using a grammar file in a C# project. I don't have any experience working with the specific grammar you indicated in an application (it's developed and maintained as part of a different project).
