### ISSUE TITLE
Cannot build with Visual Studio 2017

### ISSUE THREAD

**Issue by sharwell** [tunnelvisionlabs/antlr4cs#173]
When attempting to build a project with the Antlr4 package installed, the following error is reported.

```text
MSBUILD : error MSB4166: Child node "2" exited prematurely. Shutting down. Diagnostic information may be found in files in the temporary files directory named MSBuild_*.failure.txt.
```

Additional information is given in the MSBuild failure log:

```text
UNHANDLED EXCEPTIONS FROM PROCESS 47004:
=====================
1/12/2017 4:49:20 PM
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Build.Framework, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'Microsoft.Build.Framework, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' ---> System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Build.Framework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'Microsoft.Build.Framework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'


WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

   at Antlr4.Build.Tasks.AntlrClassGenerationTaskInternal.HandleErrorDataReceived(Object sender, DataReceivedEventArgs e)
   at System.Diagnostics.Process.ErrorReadNotifyUser(String data)
   at System.Diagnostics.AsyncStreamReader.FlushMessageQueue()
   at System.Diagnostics.AsyncStreamReader.ReadBuffer(IAsyncResult ar)
   at System.IO.Stream.ReadWriteTask.InvokeAsyncCallback(Object completedTask)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.IO.Stream.ReadWriteTask.System.Threading.Tasks.ITaskCompletionAction.Invoke(Task completingTask)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task.FinishStageThree()
   at System.Threading.Tasks.Task.FinishStageTwo()
   at System.Threading.Tasks.Task.Finish(Boolean bUserDelegateExecuted)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   at System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

**Comment by rainersigwald** [comment]
Can you get a fusion log? `Microsoft.Build.Framework, Version=4.0.0.0` should be in the framework and available everywhere . . .

**Comment by sharwell** [comment]
@rainersigwald Here's the additional lines when I turned on EnableLog:

```
=== Pre-bind state information ===
LOG: DisplayName = Microsoft.Build.Framework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
 (Fully-specified)
LOG: Appbase = file:///J:/dev/github/sharwell/antlr4cs/runtime/CSharp/packages/Antlr4.4.5.3/build
LOG: Initial PrivatePath = NULL
Calling assembly : Microsoft.Build.Utilities.v4.0, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.
===
LOG: This bind starts in default load context.
LOG: Using application configuration file: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\MSBuild.exe.Config
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
LOG: Attempting download of new URL file:///J:/dev/github/sharwell/antlr4cs/runtime/CSharp/packages/Antlr4.4.5.3/build/Microsoft.Build.Framework.DLL.
LOG: Attempting download of new URL file:///J:/dev/github/sharwell/antlr4cs/runtime/CSharp/packages/Antlr4.4.5.3/build/Microsoft.Build.Framework/Microsoft.Build.Framework.DLL.
LOG: Attempting download of new URL file:///J:/dev/github/sharwell/antlr4cs/runtime/CSharp/packages/Antlr4.4.5.3/build/Microsoft.Build.Framework.EXE.
LOG: Attempting download of new URL file:///J:/dev/github/sharwell/antlr4cs/runtime/CSharp/packages/Antlr4.4.5.3/build/Microsoft.Build.Framework/Microsoft.Build.Framework.EXE.
```

**Comment by sharwell** [comment]
If I copy Microsoft.Build.Framework 15.1.0.0 from my Visual Studio 2017 folder to the folder containing my ANTLR 4 build tasks (J:\dev\github\sharwell\antlr4cs\runtime\CSharp\packages\Antlr4.4.5.3\build), it works...

**Comment by rainersigwald** [comment]
Are you building using MSBuild.exe, VS, or a different host?

**Comment by sharwell** [comment]
> Are you building using MSBuild.exe, VS, or a different host?

Building inside Visual Studio 2017.

**Comment by ben-may** [comment]
I'm personally building both from cmd line via devenv + trying in the IDE itself both result in the same problem.

**Comment by rainersigwald** [comment]
How can I get a local repro?

**Comment by sharwell** [comment]
1. Clone this repository
2. Open runtime/CSharp/Antlr4.sln in Visual Studio 2017 (if one project fails to load, ignore it/proceed)
3. Restore NuGet packages
4. Build Antlr4.Runtime.Test.net20

**Comment by sharwell** [comment]
We're guessing this has to do with the use of app domains in the MSBuild tasks. I'll post a summary soon with some history on why that occurs and hopefully find that it's no longer as applicable as it once was.

**Comment by ben-may** [comment]
@sharwell sounds good.  when will there be a new release of this package?

**Comment by sharwell** [comment]
@ben-may I'm expecting a new pre-release build later today. Hopefully I can figure out some sort of a resolution for cross-platform users before the next stable release.

**Comment by sharwell** [comment]
@ben-may It's going to take a little longer than expected (by about a week). In the meantime, it will work if you manually copy the Microsoft.Build.Framework.dll from your Visual Studio 2017 folder into the folder on your machine containing Antlr4BuildTasks.net40.dll (it's part of the Antlr4.CodeGenerator NuGet package which your project is referencing).

**Comment by ben-may** [comment]
@sharwell thanks!  I can wait another week, I'll just continue to build it with VS2015 for now until your fix is released.

**Comment by sharwell** [comment]
I've added this to my [Versioning](https://github.com/orgs/tunnelvisionlabs/projects/1) project that I'm now using to keep track of the _many_ issues that I need to resolve to support Visual Studio 2017 in various ways.

**Comment by ben-may** [comment]
hey @sharwell any updates on a new release being posted?

**Comment by sebandraos** [comment]
@sharwell With the RTM of VS2017 today I assume there will be a few people, like me, keen to move over. Do you have a revised update estimate? Cheers

**Comment by sharwell** [comment]
@sebandraos @ben-may Should be fixed with release 4.6.1-beta001. I have several things in store for coming releases but if you can put this through it's paces I'll get a stable 4.6.1 release out and push off the other items.

**Comment by sebandraos** [comment]
Thanks Sam @sharwell I will update our relevant projects today and let you know if anything isn't working as expected.

**Comment by ben-may** [comment]
thanks @sharwell I'll try it also and see what happens :)

**Comment by ben-may** [comment]
Hey @sharwell 
Straight upgrade to that version I see this in my build error output:

1>D:\packages\Antlr4.CodeGenerator\4.6.1-beta001\Antlr4.CodeGenerator.4.6.1-beta001\build\Antlr4.CodeGenerator.targets(110,5): error AC1000: Unknown build error: The system cannot find the file specified

Any idea what file it cannot find?  Can I add any debugging flag to the Antlr4ClassGenerationTask to get more info?

**Comment by sharwell** [comment]
@ben-may 

1. What version were you upgrading from?
2. Did you restart Visual Studio after upgrading?

Try restoring NuGet packages by right clicking on the top (solution) node in Solution Explorer and restarting Visual Studio.

Is your project open source (where I can see a branch with the changes)?

**Comment by ben-may** [comment]
Upgrading from 4.5.0-alpha003

I did not restart VS, but I just tried that now, and it didn't seem to make a difference.
Unfortunately the code is not OS, so I cannot share it.

**Comment by sebandraos** [comment]
@ben-may Interesting that you found that. I did a few funny things to the project that I'm testing this on that forced me to remove and re-add the NuGet package and I have regenerated code a number of times without issue today. Obviously that is no help to you but for @sharwell 's sake it's not a ubiquitous issue. I was previously on 4.5.4-beta001 and since this update am obviously in VS2017

**Comment by sharwell** [comment]
I did find #187 when testing this in Visual Studio 2017, but otherwise it appears to be working for me. @ben-may Can you try deleting your packages folder and restoring packages again?

**Comment by ben-may** [comment]
I tried that earlier as well, but gave me the same issue.  any way I can help debug what file its trying to find?

**Comment by sharwell** [comment]
@ben-may What kind of project are you using? Your packages folder structure from the error is different from mine.

**Comment by sharwell** [comment]
@ben-may Since this doesn't appear to affect everyone, can you create a new issue for it? I believe it's project-type specific.

**Comment by ben-may** [comment]
So disregard, the issue I was happening is a local config issue, after resolving that it seems to now work.  So I think the issue is resolved for me with this 4.6.1-beta001 version.

**Comment by abergs** [comment]
@sharwell Installed beta002 and compilation worked me on VS 2017 Enterprise

**Comment by igitur** [comment]
For other people who came here with the same problem, here was my solution: https://github.com/tunnelvisionlabs/antlr4cs/issues/188#issuecomment-517621547
