### ISSUE TITLE
Unable to set grammar Build Action in .NETStandard Library in Visual Studio 2017

### ISSUE THREAD

**Issue by sebandraos** [tunnelvisionlabs/antlr4cs#193]
In a .NETStandard library, in VS2017 therefore without the ANTLR Language Support extension, I am unable to change the Build Action of the grammar file to Antlr4. I can force the Build Action by changing the csproj directly and the files are all generated as necessary but the Build Action in the grammar file properties remains None. This is using the latest NuGet package, 4.6.1-beta002.

**Comment by sharwell** [comment]
This appears to be a bug in the new project system. I filed dotnet/roslyn-project-system#1715 for it.

**Comment by sharwell** [comment]
@sebandraos Looks like there's nothing we can do about this in the current release. 😟

**Comment by sebandraos** [comment]
@sharwell Ah well, we'll have to wait and see then.
P.S. All of my tests in VS2017 are running fine.

**Comment by lextm** [comment]
@sebandraos That's going to be a long wait. They mark it for 16.0, which means should be VS vNext, not an update of VS2017.

**Comment by sharwell** [comment]
Well at least it's only a display error...

**Comment by jamesqo** [comment]
Regarding this snippet from the original post:

> in VS2017 therefore without the ANTLR Language Support extension

Are there plans to allow installing this extension on VS2017? There is an issue about this (with a lot of upvotes) [here](https://github.com/tunnelvisionlabs/LangSvcV2/issues/80) and already a pull request for it [here](https://github.com/tunnelvisionlabs/LangSvcV2/pull/81/files).

**Comment by jamesqo** [comment]
@sharwell Regarding this actual issue, I am currently trying to move a grammar and its autogenerated code into a .NET Standard library from a Xamarin app. For some reason, the code is no longer being generated. I'm using Antlr4 4.6.1. Here's my project file:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard1.4</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Antlr4" Version="4.6.1" />
    <PackageReference Include="System.Collections.Immutable" Version="1.3.1" />
  </ItemGroup>

  <ItemGroup>
    <Antlr4 Include="Internal\Languages\Java\SyntaxHighlighting\Java.g4">
      <Generator>MSBuild:Compile</Generator>
      <CustomToolNamespace>Repository.EditorServices.Internal.Languages.Java.SyntaxHighlighting</CustomToolNamespace>
    </Antlr4>
  </ItemGroup>

</Project>
```

(You can view the other files in my project [here](https://github.com/jamesqo/Repository/blob/master/Repository.EditorServices/Repository.EditorServices.csproj).)

Am I doing anything wrong? I have looked over all of the .NET Core/Standard-related issues here but no one has the same problem and is using 4.6.1-beta002 or later.
