### ISSUE TITLE
VS2017 IntelliSense reported "The name 'ErrorHandler' does not exist in the current context"

### ISSUE THREAD

**Issue by lextm** [tunnelvisionlabs/antlr4cs#194]
Error	CS0103	The name 'ErrorHandler' does not exist in the current context	SomeProject	C:\Users\lextm\Downloads\SomeParser.cs	165	Active

The project (.NET Standard 1.3 class library) compiles perfectly, but with "Build + IntelliSense" selected in Error List panel, I can see false alarm generated. If using "Build Only", of course everything is fine.

It seems to be a bug of Roslyn but who knows. You might take a look.

**Comment by sharwell** [comment]
Hi @lextm I'm pretty sure this was fixed by #219, assuming you are using the new project system in Visual Studio 2017.
