### ISSUE TITLE
Roadmap for 4.6.1

### ISSUE THREAD

**Issue by maxraab** [tunnelvisionlabs/antlr4cs#199]
Is there a roadmap for the release of 4.6.1? As mentioned in https://github.com/antlr/antlr4/issues/1828 the current beta release fixes an issue with VS2017.
Unfortunately this problem prevents us from upgrading our infrastructure since we cannot use pre-releases.

/cc @sharwell

**Comment by sharwell** [comment]
I have one small item to fix for it, but it should be easy.

**Comment by maxraab** [comment]
Are there any news?

**Comment by Sabmit** [comment]
Hi @sharwell,

Can we get more informations about this issue?
I'm planning to use this version, but I don't know if I should wait for the RCs

**Comment by sharwell** [comment]
I'll try to get it published by EOD Saturday

**Comment by GeirGrusom** [comment]
Thanks for all your work, @sharwell. It's greatly appreciated.

**Comment by Sabmit** [comment]
Thanks for you quick answer and your good work !

**Comment by sharwell** [comment]
Bad news and good news:

Bad: I spent the weekend sick and didn't make this deadline.
Good: It just became a relevant issue at work work.

**Comment by sharwell** [comment]
I just pushed 4.6.1 to NuGet. 👍
