### ISSUE TITLE
nothing happens

### ISSUE THREAD

**Issue by tdjastrzebski** [tunnelvisionlabs/antlr4cs#203]
I installed latest VS 2015 "ANTLR Language Support" extension and restarted VS.
Next I added existing g3 combined grammar/lexer, referenced Antlr3 nugget package, including the Runtime.
G3 file properties look good (Build Action=Antlr3, Custom Tool=MSBuild:Compile) but when I rebuild the project nothing happens, Lexer/Parser classes do not get generated, no errors displayed.
What am I missing? Java runtime is no longer required, is it?

**Comment by lextm** [comment]
The lexer and parser files are in the folder `obj/Debug` if you are working on a debug build.

**Comment by tdjastrzebski** [comment]
Thank you!
obj/Debug is the place where I would not look for those files since adding g3/g4 files lexer/parser c# source files are generated underneath with *.g3.lexer.
Is not it a bug?

![image](https://user-images.githubusercontent.com/7325277/27086459-88d311de-5052-11e7-88e4-ccf4d0ecaf71.png)

**Comment by tdjastrzebski** [comment]
OK, so generated files should only be present in OBJ folder.
Now, tool Antlr3 generated parser rules are all marked 'private'.
Is there any way to modify it?

**Comment by tdjastrzebski** [comment]
Ok, so, when g3 file is added to the project those *.g3.lexer.cs and and *.g3.parser.cs files should not be generated. After removing them it almost compiles - see #205

**Comment by sharwell** [comment]
:memo: This is the repository for ANTLR 4, which does not support the feature you describe. The repository for the ANTLR 3 C# target is [antlr/antlrcs](https://github.com/antlr/antlrcs).

> when g3 file is added to the project those *.g3.lexer.cs and and *.g3.parser.cs files should not be generated

This is actually a feature of both the ANTLR 3 and ANTLR 4 C# releases. These files allow you to write C# code which is added to the same `partial class` as the generated code, but is placed in a different file. The Windows Forms and XAML designers both do the same thing.

**Comment by lextm** [comment]
@sharwell Most users won't know this for the first time. So you might put it somewhere more explicit. Especially for ANTLR 3 and 4, it is very important to know where such files locate, and then you can open them in VS and set break points to debug the code.

**Comment by sharwell** [comment]
@lextm I filed #206 for that.

**Comment by tdjastrzebski** [comment]
I believe lexer/parser code should be placed in *.g3.lexer.cs and and *.g3.parser.cs files 'under' the grammar file - but it is not. It gets placed in OBJ folder.

**Comment by sharwell** [comment]
@tdjastrzebski The base location of the generated files has not changed since I first implemented it in Oct. 2009. It's late now, but if you want I can explain some of the reasons behind the original decision tomorrow (let me know if you are interested).

> Needless to say, this way code pulled from the repository will not compile without the "ANTLR Language Support" tool while otherwise it would.

There is no need to have the ANTLR Language Support extension installed, although it does make some things easier. The only thing you do need is to install the NuGet package which provides the build support ([Antlr3](https://www.nuget.org/packages/Antlr3) or [Antlr4](https://www.nuget.org/packages/Antlr4), depending on the version you use).

**Comment by tdjastrzebski** [comment]
@sharwell I think more standard approach (that is, code generated 'under' g3/g4 files) would greatly improve the initial experience. Adding ANTLR grammar file (both g3 and g4) via 'add new' results in separate *.g3.lexer.cs and *.g3.parser.cs being added but upon build the content does not change. I think that was the main source of my confusion. Anyway, thank you for keeping ANTLR alive.

![image](https://user-images.githubusercontent.com/7325277/27172772-a66a2380-51b6-11e7-923d-5e226a5aec90.png)

![image](https://user-images.githubusercontent.com/7325277/27172805-c070da8a-51b6-11e7-8758-e8f7a2ec6ec5.png)

![image](https://user-images.githubusercontent.com/7325277/27172843-e2851834-51b6-11e7-9b3b-6a77438e7791.png)

**Comment by lextm** [comment]
@tdjastrzebski That would be a source control unfriendly approach. Automatic generated files should not be put into the project folder (I know resx and WinForms, but that was designed in the old days).

**Comment by tdjastrzebski** [comment]
@lextm ASP.Net forms 'designer' classes, EF/EDMX data entities are generated the same way, EF Core generated entities and similar are typically placed with the rest of the source code etc. The practice of generating source code into obj folder is not standard. Actually, it is the first time I see such solution.
Why you call it 'source control unfriendly approach'? Current approach is dangerous. The danger is at certain point of time in the future project is restored from repository to some other build environment (without obj folder) and will no longer compile while your tool is no longer supported - at all or just for this build environment. After all, nothing lasts forever.

I guess, this could be a matter of endless debate so let's drop it since this is not my main point

My point is it is 'ANTLR Language Support" tool which creates separate .g3.lexer.cs/.g3.parser.cs files but then generated code goes to the obj folder. See the screenshots I included.

**Comment by tdjastrzebski** [comment]
@lextm Also, I am not sure I understand "source control friendly approach". Two *.cs files less in the repository changing when the g3/g4 files change? Och, come on.

**Comment by lextm** [comment]
@tdjastrzebski but once the generated files change, you will see miserable diff. That can lead to significant problems when you need to merge among branches.

WinForms files are typical examples in the past, which bothers too many people. Though I agree grammar files change less frequently, leaving the generated files out of sight can ultimately solve this issue for all.

**Comment by tdjastrzebski** [comment]
@lextm There is nothing which forces developer to commit changes with each change in grammar file.
I think solving this not such a big problem you created bigger issues - as I described.
Anyway, I am done with changes I had to make, moved parser/lever *.cs files to the project root where they belong to, uninstalled ANTLR besides runtime and I am good to go. Thanks for a good discussion.

**Comment by sharwell** [comment]
@tdjastrzebski One of the design requirements for this project is the isolated action of running a build is not allowed to change files that are checked into source control. There are two reasons why this is a requirement (meaning no option that did not provide this was even considered):

1. Some source control systems lock files (read only). In these cases, attempting to modified the files during the build would either cause the build to fail (couldn't write to the file) or be invalid (completed compilation but used an old version of the file).
2. Some versions of some IDEs do not update their copy of certain files during the build process if those files change *during* the build. In these versions of these IDEs, the first time you build it would use an old copy of the generated code, and then you would have to build the project again to get the new copy. There was no warning or indication of any kind that the build was not correct in these cases.

**Comment by tdjastrzebski** [comment]
@sharwell Next time I may need to do some more changes may be in VS 2020 .Net Framework 5.5. Do you guarantee ANTLR build process as is will be supported?
If I ever modify the grammar file I would know I have to recreate parser/lexer.
The only source control system I care about these days is Git.
I am not saying the parser/lexer code should modify during the build but I would expect VS extension to modify the code when the grammar file is saved. Although, modifying source during the (pre)build is not entirely uncommon. Maybe both ways should/could be supported? - it is just a thought.
But I understand your design decisions.

**Comment by sharwell** [comment]
> Next time I may need to do some more changes may be in VS 2020 .Net Framework 5.5. Do you guarantee ANTLR build process as is will be supported?

I've never made any guarantees, but history suggests the chances are good.

> I am not saying the parser/lexer code should modify during the build but I would expect VS extension to modify the code when the grammar file is saved.

The code is modified when the grammar is saved, and you don't need the VS extension installed to have this work.

> Maybe both ways should/could be supported? - it is just a thought.

The way I chose is the one way to guarantee the build output does what the user expected. In each alternative suggested to date, there are examples of project configurations and/or usage scenarios where the build could contain compiled code which does not match the grammar. This represents a critical failure of a build system and must not be made readily available.

With that said, I do not forcibly prevent users from allowing a build to be invalid. As you have discovered, it is possible to remove the grammar generation step from the build altogether and just include the generated files manually. The good news though is it required substantial investigation and manual intervention on your part to "break out of the box" of safety the build system otherwise included.

**Comment by tdjastrzebski** [comment]
And I did it because I did not FEEL safe. Maybe it is just bad experience.
Perhaps other users just have a different perspective.
