### ISSUE TITLE
Can the antlr generate csharp interface code fileName start with ‘I’？

### ISSUE THREAD

**Issue by mokeyish** [tunnelvisionlabs/antlr4cs#207]

**Comment by sharwell** [comment]
It perhaps could, but this file is also an intermediate build artifact that's never really exposed for editing. The header is intentionally written to avoid triggering even strict checks for file name, such as a user setting [SA1649](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1649.md) to Error severity. Can you describe the problem that you're encountering as a result?

**Comment by mokeyish** [comment]
@sharwell Think you for your replying，I try to use antlr4 with .NET standard 1.6,but it seems dose not reference the generated code file  . I want copy the the generated code file to project directly ,but the fileName ...

**Comment by sharwell** [comment]
@mokeyish Can you file a bug describing the steps to reproduce the issue? The most recent release (4.6.1) is *supposed* to support .NET Standard scenarios, meaning everything should just work without having to take manual steps.

**Comment by mokeyish** [comment]
@sharwell , Ha ha ~ ,I find a better way to reference the generated code file just now .and it works well.Select the reference the generated code file in ‘obj/debug’, then right click include in project. here is the scrrenshot of ‘project.csprj’ file 。
![baidushurufa_2017-6-20_12-49-45](https://user-images.githubusercontent.com/16131917/27317137-1e1144b4-55b7-11e7-9d34-fcba9e229583.png)
