### ISSUE TITLE
Compilation Issues on .NET Core

### ISSUE THREAD

**Issue by tsutomi** [tunnelvisionlabs/antlr4cs#208]
I've posted this issue as comment to another issue, but in that conversation I've been informed the causes are different.

I am developing a SQL system ([DeveelDB](https://github.com/deveel/deveeldb.core)) based on .NET Core framework, using ANTLRv4 for the SQL parsing.
The project is a .NET Core with Visual Studio 2017 project model (MSBuild), targeting the version 1.1 of the framework: in all of my own machines (2 laptops and one desktop) the compilation and tests are all successful.

The peojects start to fail once built on [AppVeyor](https://ci.appveyor.com/project/Deveel/deveeldb-core/build/1.0.0-115) and [Travis](https://travis-ci.org/deveel/deveeldb.core/builds/245396700).

I've references all the libraries for the build (_Microsoft.Build.Framework v15.1.1012_, _Microsoft.Build.Tasks.Core v15.1.1012_ and _Microsoft.Build.Utilities.Core v15.1.1012_), without effects, as it is visible in the build log that can be seen in the CI linked

**Comment by VHaravy** [comment]
I have seen a similar issue with my projects as well. It seems that `Antlr4BuildTasks.dll` assembly references MSBuild assemblies with version 4.0 that are not present when using .NET Core. I suggest to reference MSBuild libraries from [NuGet](https://www.nuget.org/packages/Microsoft.Build.Framework/15.1.1012) and moreover it might be better to include them into the Antlr4's NuGet package.

**Comment by tsutomi** [comment]
@VHaravy I have referenced all the build libraries, as I described in my issue report, but it still didn't work: I presume the libraries for .NET Core are not the same used by ANTLRv4 tasks

**Comment by tsutomi** [comment]
I posted the question to the AppVeyor's team and they fixed the issue by removing the `--configuration Release` switch in the `dotnet test` script.
Curiosly, anyway, the same didn't happen on Travis, that probably uses a different build image than AppVeyor's
