### ISSUE TITLE
Antlr4ClassGenerationTask Fails with missing dependencies on NETStandard

### ISSUE THREAD

**Issue by sebandraos** [tunnelvisionlabs/antlr4cs#216]
Hi Sam,
I'm having some issues with the latest versions of ANTLR on NETStandard. Namely when I build the Antlr4ClassGenerationTask throws because 
`Error	AC1000	Unknown build error: Could not load file or assembly 'System.Diagnostics.Process, Version=4.0.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.	ANTLRStandard	C:\Users\xxxx\.nuget\packages\antlr4.codegenerator\4.6.2\build\Antlr4.CodeGenerator.targets	110`. 
Locally I'm getting `System.Diagnostics.Process` but on our build server it's `'System.IO.FileSystem, Version=4.0.1.0, ...'`. 
I am able to repro this by creating a new .NETStandard1.4 (haven't tried other versions of NETStandard) library, adding a new grammar, editing the csproj as necessary and hitting build in VS2017. This is using the new .csproj system and referencing ANTLR4 v4.6.2 via nuget. [Minimal repro is up here.](https://github.com/sebandraos/ANTLRStandard)
I found [this](https://github.com/ctaggart/SourceLink/issues/156) similar sounding issue but I'm not familiar enough with the MSBuild process to know if it's strictly relevant.
Any help is much appreciated and don't hesitate to let me know if you need any more info or if you can't repro.

**Comment by tsutomi** [comment]
I am encountering the exact same problem. Actually I was about to report this issue with evidences, but then I found this report.
In my case, anyway, the error occurrs with .NET Core 1.0 and .NET Core 1.1

The curious part in my case is that the build works (with some issues given by style rules) when building through console (through `dotnet build`).

![antlr4-codegenerator-builderror](https://user-images.githubusercontent.com/645285/28068263-08efe830-6645-11e7-866a-f7f6aaa7dc4e.png)
![antlr4-codegenerator-buildsuccess](https://user-images.githubusercontent.com/645285/28068264-08f67d4e-6645-11e7-8bfa-d317fb36291c.png)

**Comment by sharwell** [comment]
Thanks for the repro case 👍 I should have this fixed and uploaded shortly.

**Comment by sharwell** [comment]
4.6.3 is now uploaded 🎉

**Comment by sebandraos** [comment]
I can confirm this is now working. Incredible reaction speeds Sam, always hugely appreciated.
