### ISSUE TITLE
Generation fails on microsoft/dotnet Docker image

### ISSUE THREAD

**Issue by VHaravy** [tunnelvisionlabs/antlr4cs#220]
Version 4.6.4 solved compilations issues I have had when using `dotnet` CLI tool and/or Visual Studio 2017. But there are some issues with using ANTLR4 on Linux. On my work Linux VM everything is working fine, but I have tried to use `microsoft/dotnet` Docker image for building on CI. The project does not compile. After some investigation I have found this line in the build log:

````
Executing command: "/root/.nuget/packages/antlr4.codegenerator/4.6.4/build/../tools/ikvm.exe" -cp /root/.nuget/packages/antlr4.codegenerator/4.6.4/build/../tools/antlr4-csharp-4.6.4-complete.jar org.antlr.v4.CSharpTool -o obj/Debug/netstandard1.3/ -encoding UTF-8 -listener -visitor -Dlanguage=CSharp -package Test.Implemenation /project/TestLexer.g4 /project/TestParser.g4
````

Trying to run the command above by hand I have got the following error:

````
bash: /root/.nuget/packages/antlr4.codegenerator/4.6.4/build/../tools/ikvm.exe: No such file or directory
````

Trying to get more information about the file gets me the following:

```
root@04f7f975c61e:/project/csharp# ls -alF /root/.nuget/packages/antlr4.codegenerator/4.6.4/build/../tools/ikvm.exe
-rwxr--r-- 1 root root 15872 Jul 11 21:41 /root/.nuget/packages/antlr4.codegenerator/4.6.4/build/../tools/ikvm.exe*
root@04f7f975c61e:/project/csharp# chmod +x /root/.nuget/packages/antlr4.codegenerator/4.6.4/build/../tools/ikvm.exe
```

After that results are the same:

```
bash: /root/.nuget/packages/antlr4.codegenerator/4.6.4/build/../tools/ikvm.exe: No such file or directory
```

This is probably related to the #130 and in fact, is a continuation of #208. I will try to investigate if everything works when Java is installed. Let me know how I can be of further help.

**Comment by sharwell** [comment]
@VHaravy If you run `chmod +x` manually after restoring packages, does the build work? For example, try doing this before the build:

```
nuget restore
chmod +x /root/.nuget/packages/antlr4.codegenerator/4.6.4/tools/ikvm.exe
```

**Comment by sharwell** [comment]
This may be caused by https://github.com/NuGet/Home/issues/4424.

**Comment by VHaravy** [comment]
@sharwell No, it did not. I have updated my answer (just forgot to add the results). It seems that `ikvm.exe` requires Mono or should be run in some different way. I have tried to run it with .NET CLI:
````
root@04f7f975c61e:/project/csharp# dotnet /root/.nuget/packages/antlr4.codegenerator/4.6.4/build/../tools/ikvm.exe                                                                                                                         
A fatal error was encountered. The library 'libhostpolicy.so' required to execute the application was not found in '/root/.nuget/packages/antlr4.codegenerator/4.6.4/tools'.
````

**Comment by sharwell** [comment]
I actually ported the entire code generator from Java to .NET Standard. I just need to add it to the NuGet package and provide a property that you can add to your project file to enable it.

**Comment by VHaravy** [comment]
@sharwell This is very good idea.

By the way, installing Java did not help. I have hoped that using IKVM is just a fallback, but it seems not.

**Comment by sharwell** [comment]
@VHaravy It should work as long as the `JAVA_HOME` environment variable is defined and the executable is located at `$JAVA_HOME/bin/java`.
