### ISSUE TITLE
IKVM fails with ArrayStoreException on Visual Studio for Mac

### ISSUE THREAD

**Issue by monty241** [tunnelvisionlabs/antlr4cs#242]
When running latest version of Visual Studio for Mac the code generator rails due to a Java exception when the package is 4.6.5beta001:

**Comment by monty241** [comment]
Might be solved by issue #220.

**Comment by monty241** [comment]
I have been testing with nuget 4.6.5 beta 1, but that one gives on visual studio for mac:

Target Antlr4Compile:
    Executing command: "/Users/gle3/Projects/v1/repos/itgen/dotnet/Invantive/packages/Antlr4.CodeGenerator.4.6.5-beta001/build/../tools/ikvm.exe" -cp /Users/gle3/Projects/v1/repos/itgen/dotnet/Invantive/packages/Antlr4.CodeGenerator.4.6.5-beta001/build/../tools/antlr4-csharp-4.6.5-SNAPSHOT-complete.jar org.antlr.v4.CSharpTool -o obj/Debug/ -encoding UTF-8 -listener -visitor -Dlanguage=CSharp -package Invantive.Sql /Users/gle3/Projects/v1/repos/itgen/dotnet/Invantive/Invantive.Data/Sql/InvantiveSQL.g4 /Users/gle3/Projects/v1/repos/itgen/dotnet/Invantive/Invantive.Data/Sql/InvantiveSQLTokens.g4
    /Users/gle3/Projects/v1/repos/itgen/dotnet/Invantive/packages/Antlr4.CodeGenerator.4.6.5-beta001/build/Antlr4.CodeGenerator.targets(121,5): error AC1000: Unknown build error: Exception in thread "main" java.lang.ExceptionInInitializerError
    /Users/gle3/Projects/v1/repos/itgen/dotnet/Invantive/packages/Antlr4.CodeGenerator.4.6.5-beta001/build/Antlr4.CodeGenerator.targets(121,5): error AC1000: Unknown build error: Caused by: java.lang.ArrayStoreException
    /Users/gle3/Projects/v1/repos/itgen/dotnet/Invantive/packages/Antlr4.CodeGenerator.4.6.5-beta001/build/Antlr4.CodeGenerator.targets(121,5): error AC1000: Unknown build error: 	at org.antlr.v4.Tool.<clinit>(Tool.java)
Done building target "Antlr4Compil

**Comment by sharwell** [comment]
@monty241 I decided to resolve the IKVM issue finally by porting the entire ANTLR 4 tool from Java to C# in a way that supports .NET Standard. In 4.6.5 Beta 1, this new code generator is available only by manually selecting it (the next release will include #236, which automatically enables the new code generator when Java cannot be found). You can manually enable the new code generator by following the instructions in the [release notes for 4.6.5 Beta 1](https://github.com/tunnelvisionlabs/antlr4cs/releases/tag/v4.6.5-beta001).

**Comment by monty241** [comment]
OK thanks, saves layers. Will test with changes on mac.
