### ISSUE TITLE
Event EnterVsStruct don't fire

### ISSUE THREAD

**Issue by lsalamon** [tunnelvisionlabs/antlr4cs#257]
<b>For exact lines:</b>
<pre>
Public Function CheckReg(ByVal sXML As String)
Dim oDocXML As MSXML2.DOMDocument40
oDocXML.loadXML (sXML)
End Function
</pre>
<b>Event EnterVsStruct don't fire but fire event ExitVsStruct.</b>

My env:
Antlr4 {4.6.4} VisualBasic6
Antlr4.CodeGenerator {4.6.4} VisualBasic6
Antlr4.Runtime {4.6.4} VisualBasic6

Visual Studio 2017 Community 15.4.4
Windows 10 (1709)

**Comment by sharwell** [comment]
Duplicate of #259
