### ISSUE TITLE
Event EnterVsNot don't fire

### ISSUE THREAD

**Issue by lsalamon** [tunnelvisionlabs/antlr4cs#258]
<b>For exact lines:</b>
<pre>
Public Function CheckBool(ByVal bVal As Boolean) As Boolean
    If Not bVal Is Nothing Then
       CheckBool = True
    Else
       CheckBool = False
    End If
End Function
</pre>

<b>Event EnterVsNot don't fire but fire event ExitVsNot.</b>

My env:
Antlr4 {4.6.4} VisualBasic6
Antlr4.CodeGenerator {4.6.4} VisualBasic6
Antlr4.Runtime {4.6.4} VisualBasic6

Visual Studio 2017 Community 15.4.4
Windows 10 (1709)

**Comment by sharwell** [comment]
Duplicate of #259
