### ISSUE TITLE
Runtime for C# 4

### ISSUE THREAD

**Issue by skrilmps** [tunnelvisionlabs/antlr4cs#260]
Hello, is there an ANTLR runtime that is compatible with C# version 4.x?

I ask because I'm trying to get the ANTLR runtime working inside Unity, which only supports up to C# 4.

Thanks.

**Comment by sharwell** [comment]
The ANTLR runtime has two version requirements:

* The runtime library is pre-built, so it depends only on the version of the .NET Framework (or other runtime). The NuGet package supports almost every version of .NET since .NET 2.0, and should not have a compatibility problem.
* The generated source code is C#, and thus could impose a limit on certain language features.

I am not currently aware of any features of the generated code which rely on C# versions greater than 4.

**Comment by skrilmps** [comment]
I was getting the error "Feature `null propagating operator' cannot be used because it is not part of the C# 4.0 language specification" in cases where the ? operator was being used.

**Comment by sharwell** [comment]
@skrilmps The null propagating operators (`?.` and `?[`) are not used in the generated code:

https://github.com/tunnelvisionlabs/antlr4cs/blob/master/tool/resources/org/antlr/v4/tool/templates/codegen/CSharp/CSharp.stg

Can you describe the steps to reproduce this issue?

**Comment by skrilmps** [comment]
Unfortunately I've been unable to reproduce that error message because I have a different one now.

Here are the steps I've taken towards getting ANTLR to work inside Unity (I am using Unity version 2017.2.0f3 on Mac OS X High Sierra):

1) Download Antlr4 C# runtime v4.7 from here: http://www.antlr.org/download/antlr-csharp-runtime-4.7.zip 
2) Set Unity to build using .NET version 3.5 (my only other option is 4.6)
3) Import the downloaded Antlr4.Runtime.Standard.dll into Unity project
4) Install antlr version 4.7 for use on the command line
5) Run java -jar /usr/local/lib/antlr-4.7-complete.jar -visitor -Dlanguage=CSharp manuscript.g4 to generate the parser code in C#
[ Note: when I try to specify a version number for CSharp, for instance '-Dlanguage=CSharp_v4_5' I get 'error(31):  ANTLR cannot generate CSharp_v4_5 code as of version 4.7'.  So I do not know exactly what version of C# the generated parser is using. ]
6) Import the generated C# parser into Unity project

At this stage I get 4 errors, all in manuscriptParser.cs (one of the generated files) that say:
error CS0115: `manuscriptParser.Vocabulary' is marked as an override but no suitable property found to override
error CS0115: `manuscriptParser.GrammarFileName' is marked as an override but no suitable property found to 
error CS0115: `manuscriptParser.RuleNames' is marked as an override but no suitable property found to override
error CS0115: `manuscriptParser.SerializedAtn' is marked as an override but no suitable property found to override

I wish I had more info but I hope that helps at least shed some light.  Thank you for your time and help!

**Comment by sharwell** [comment]
@skrilmps Based on those steps, it sounds like you are using the Antlr4.Runtime.Standard package. The original C# target created by me is published in the [Antlr4.Runtime](https://nuget.org/packages/Antlr4.Runtime) package, and the code generator for it is published in the [Antlr4.CodeGenerator](https://nuget.org/packages/Antlr4.CodeGenerator) package. Steps 1, 3, 4, 5, and 6 from your list above are not supported for this target.

* Steps 1, 4, 5, and 6 are automatically run during the build after installing the Antlr4.CodeGenerator package
* Step 3 uses the Antlr4.Runtime package instead of the Antlr4.Runtime.Standard package

You can find more information in the readme for this repository.

**Comment by skrilmps** [comment]
Thanks.  I'd already tried following your readme.  However many of the steps in the readme don't appear to work with my version of Visual Studio, so I moved to trying the command-line approach.  I am using the latest version of VS that I found for Mac, which is Visual Studio Community for Mac version 7.2.2

**Comment by sharwell** [comment]
@skrilmps the code generator runs during the build and doesn't actually depend on Visual Studio at all. However, despite working with both msbuild and dotnet on Windows, there are a few remaining bugs that prevent the current release from working on non-Windows build systems.

**Comment by skrilmps** [comment]
Thanks for your help!

**Comment by skrilmps** [comment]
Thanks for your help!

**Comment by skrilmps** [comment]
After some trial and error I was able to get ANTLR working on Unity on the Mac.  It required using both Visual Studio on Windows as well as Unity on Mac.  A little round-about, perhaps, but it works.  In case it's useful to anyone else, here are the steps I followed:

	1.	Install Visual Studio Community 2017 on Windows
	⁃	Install the folllowing:
	⁃	Visual Studio core editor (there by default)
	⁃	.NET desktop development (under Workloads)
	⁃	NuGet package manager (under Individual Components -> Code tools)
	2.	From Visual Studio 2017 on Windows:
	⁃	Create a new Project
	⁃	Select Windows Classic Desktop
	⁃	Select any(?) .NET Framework app
	⁃	Right-click project name and select Properties and verify version of .NET Framework (in my case it’s 4.6.1)
	3.	Follow Readme Step 4 to use NuGet to install ANTLR4 here: 
	⁃	https://github.com/tunnelvisionlabs/antlr4cs
	⁃	Install ANTLR version 4.6.4 (or latest stable)
	4.	Add grammar file (.g4) to Project
	5.	Choose Save As… for the g4 file and click the dropdown box next to Save and select “Save with Encoding…”
	⁃	Choose Unicode (UTF-8 without signature)
	6.	Follow Readme Step 2 of “Add an existing grammar to a project” here: 
	⁃	https://github.com/tunnelvisionlabs/antlr4cs
	⁃	Make sure to also manually edit the project file as described
	7.	Restart Visual Studio and reload project
	8.	Select Build -> Build Solution
	9.	Look in repos/projectName/projectName/obj/Debug to find the generated files
	⁃	copy *.tokens and *.cs to a new folder
	10.	Move to Unity on Mac
	⁃	import the folder with the generated files into Unity
	11.	On Mac, use command-line nuget to install the ANTLR runtime:
	⁃	nuget install Antlr4 -Version 4.6.4 (or whatever latest stable version used in step 3 above)
	⁃	Folders will be installed to the CWD
	12.	Open subdirectory Antlr4.Runtime.4.6.4/lib and then choose the folder of the corresponding .NET version as used in step 2 (in my case the closest one is net4.5)
	13.	Import Antlr4.Runtime.dll from that subdirectory into your Unity project

**Comment by skrilmps** [comment]
In doing the above steps, I do still get some warnings, both from Unity and from Visual Studio.  They're all of the same type:

warning CS3021: `className' does not need a CLSCompliant attribute because the assembly is not marked as CLS-compliant

**Comment by sharwell** [comment]
@skrilmps you need to add the following to your **AssemblyInfo.cs** file:

```csharp
[assembly: CLSCompliant(false)]
```

**Comment by skrilmps** [comment]
OK thanks.  Warnings went away.

I updated my post above to include the extra steps.
