### ISSUE TITLE
How to use it on vs2017? 

### ISSUE THREAD

**Issue by NMSAzulX** [tunnelvisionlabs/antlr4cs#261]

**Comment by GeorgDangl** [comment]
You have to configure it as a build task:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  
  <ItemGroup>
    <PackageReference Include="Antlr4.Runtime" Version="4.6.4" />
    <PackageReference Include="Antlr4.CodeGenerator" Version="4.6.5-beta001">
      <PrivateAssets>All</PrivateAssets>
    </PackageReference>
  </ItemGroup>
  
  <ItemGroup>
    <Antlr4 Include="Calculator.g4">
      <Generator>MSBuild:Compile</Generator>
      <CustomToolNamespace>Dangl.Calculator.Generated</CustomToolNamespace>
      <Listener>False</Listener>
      <Visitor>True</Visitor>
    </Antlr4>
  </ItemGroup>

  <!-- Use this if you don't want to depend on the Java tool -->
  <PropertyGroup>
    <Antlr4UseCSharpGenerator>True</Antlr4UseCSharpGenerator>
  </PropertyGroup>
  
</Project>
```

[Example project](https://github.com/GeorgDangl/Dangl.Calculator)

**Comment by NMSLanX** [comment]
Tks. And I can't find a template about Antlr4 on VS.

**Comment by GeorgDangl** [comment]
Yeah I think there's no support yet, neither for the language extension (syntax highlighting) or templates (creating grammar / lexer files).

**Comment by sharwell** [comment]
@NMSLanX @GeorgDangl There isn't a new extension uploaded, but you can download the latest build for the original source repository ([tunnelvisionlabs/LangSvcV2](https://github.com/tunnelvisionlabs/LangSvcV2)). Here is a link to the artifacts from the latest build:
https://ci.appveyor.com/project/sharwell/langsvcv2/branch/master/artifacts

The ANTLR support (both ANTLR 3 and 4) is in the extension **Tvl.VisualStudio.Language.Antlr3.vsix**.

**Comment by fqybzhangji** [comment]
@sharwell
Thank you for solving my problem
