### ISSUE TITLE
Support for Visual Studio Community

### ISSUE THREAD

**Issue by dhowe** [tunnelvisionlabs/antlr4cs#267]
Would be great if you could support (and include a simple test project) for current versions of Visual Studio Community (without the extension). I'm having all sorts of problems getting a simple ANTLR4 c# project running.

**Comment by lextm** [comment]
Please be fair and show the "problems" you met.

I did a new project recently and never experienced "all sorts of problems", and note that my project is far more than "a simple ANTLR 4 C# project",

https://github.com/lextm/restructuredtext-antlr

**Comment by dhowe** [comment]
Sorry about that -- I can be more detailed, just wasn't sure if you had worked with VS2017 Community. Should I write it up here, or in https://github.com/lextm/restructuredtext-antlr/issues ?

**Comment by lextm** [comment]
You should describe the problems you met here, as the ANTLR C# runtime developers are all here watching.

In most cases, if you hit an error message, it should have been discussed somewhere in this repo (so GitHub search or Google site search should tell). If you happen to hit a very special issue, I believe it can be further investigated and resolved.

My project works fine in both Visual Studio 2017 and JetBrains Rider, so if you want to analyze a working project, it can serve as a sample (though too complicated).

**Comment by dhowe** [comment]
Ok, so I'm trying to setup a simple skeleton C# project with Antlr4 in Visual Studio Community Edition, which, as best I can tell, does not support extensions. 

My attempt:

1. Open VS 2017 and create a new console project called 'TestAntlr'

![image](https://user-images.githubusercontent.com/737638/34642576-1722d26c-f350-11e7-8be8-d666faa5bba0.png)

2. Editor opens with the following Program.cs, which runs without problem in an external terminal (on OS X)

````
using System;

namespace TestAntlr
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
        }
    }
}

3.Right click dependencies and add Antlr4

![screen shot 2018-01-07 at 2 14 01 am](https://user-images.githubusercontent.com/737638/34642593-7cc5987a-f350-11e7-86a6-25a8e6b01edd.png)

4. After downloading and accepting license, I see:

![image](https://user-images.githubusercontent.com/737638/34642601-9b56e97e-f350-11e7-9198-10601b03da9d.png)

5. I create a test .g4 file, unload and reload the project, but cannot get it compile within VS17, according to the instructions in the README. I can compile from the command-line using a custom Java command, however then the generated C# code will not run (more details to come).

**Comment by retailcoder** [comment]
FWIW I'm running R# in VS Community 2017, it absolutely supports extensions.

**Comment by lextm** [comment]
Well, just noticed you are using Visual Studio for Mac. Not a big deal, but it does require something more.

One trouble is that you need to manually edit the project file, to use `Antlr4` as Build action for your grammar file, and also specify Java path manually (as `Antlr4JavaExecutable`),
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Antlr4JavaExecutable Condition=" '$(OS)' != 'Windows_NT' ">/usr/bin/java</Antlr4JavaExecutable>
    <TargetFrameworks>netstandard1.3</TargetFrameworks>
```
Your grammar file should also show an option to use CSharp as target language,
```
grammar ReStructuredText;

options {
  language=CSharp;
}

@parser::namespace { Lextm.ReStructuredText }
@lexer::namespace { Lextm.ReStructuredText }

parse

  :  (element | empty_line)+? EOF
  ;
```

**Comment by dhowe** [comment]
@retailcoder Re: extensions, I think the trouble is the platform (OS X), not the Community edition...

**Comment by dhowe** [comment]
thanks @lextm is it possible for you to include the full .csproj file?

**Comment by lextm** [comment]
@dhowe I gave you the whole repo above. Take your time.

**Comment by dhowe** [comment]
Ok, so with those additions, and a bunch of warnings, I seem to be able to generate .cs files. Can someone help me to a) check these errors (below) and b) run my visitor from the IDE ?

````
/Users/dhowe/git/TestAntlr/TestAntlr/CustomLanguage.g4(5,5): Warning: Unknown build error: Exception in thread "main" cli.System.NotSupportedException: The invoked member is not supported in a dynamic module. (TestAntlr)
/Users/dhowe/git/TestAntlr/TestAntlr/CustomLanguage.g4(5,5): Warning: Unknown build error: 	at cli.System.Reflection.Emit.TypeBuilder.check_created(Unknown Source) (TestAntlr)
/Users/dhowe/git/TestAntlr/TestAntlr/CustomLanguage.g4(5,5): Warning: Unknown build error: 	at cli.System.Reflection.Emit.TypeBuilder.RuntimeResolve(Unknown Source) (TestAntlr)
/Users/dhowe/git/TestAntlr/TestAntlr/CustomLanguage.g4(5,5): Warning: Unknown build error: 	at cli.System.Reflection.Emit.ModuleBuilder.RuntimeResolve(Unknown Source) (TestAntlr)
/Users/dhowe/git/TestAntlr/TestAntlr/obj/Debug/netcoreapp2.0/CustomLanguageLexer.cs(22,22): Warning CS3021: 'CustomLanguageLexer' does not need a CLSCompliant attribute because the assembly does not have a CLSCompliant attribute (CS3021) (TestAntlr)
/Users/dhowe/git/TestAntlr/TestAntlr/obj/Debug/netcoreapp2.0/CustomLanguageListener.cs(18,18): Warning CS3021: 'ICustomLanguageListener' does not need a CLSCompliant attribute because the assembly does not have a CLSCompliant attribute (CS3021) (TestAntlr)
/Users/dhowe/git/TestAntlr/TestAntlr/obj/Debug/netcoreapp2.0/CustomLanguageParser.cs(22,22): Warning CS3021: 'CustomLanguageParser' does not need a CLSCompliant attribute because the assembly does not have a CLSCompliant attribute (CS3021) (TestAntlr)
/Users/dhowe/git/TestAntlr/TestAntlr/obj/Debug/netcoreapp2.0/CustomLanguageBaseListener.cs(22,22): Warning CS3021: 'CustomLanguageBaseListener' does not need a CLSCompliant attribute because the assembly does not have a CLSCompliant attribute (CS3021) (TestAntlr)
/Users/dhowe/git/TestAntlr/TestAntlr/obj/Debug/netcoreapp2.0/CustomLanguageVisitor.cs(18,18): Warning CS3021: 'ICustomLanguageVisitor<Result>' does not need a CLSCompliant attribute because the assembly does not have a CLSCompliant attribute (CS3021) (TestAntlr)
/Users/dhowe/git/TestAntlr/TestAntlr/obj/Debug/netcoreapp2.0/CustomLanguageBaseVisitor.cs(22,22): Warning CS3021: 'CustomLanguageBaseVisitor<Result>' does not need a CLSCompliant attribute because the assembly does not have a CLSCompliant attribute (CS3021) (TestAntlr)
````

**Comment by dSerk** [comment]
oe whatever kissinse 
 "Everybody gets so much information all day long that they lose their common sense." -Gertrude Stein "So... The shit's about to match coordinates with the fan." -Alastair Reynolds 

    On Saturday, January 6, 2018 2:14 PM, Lex Li <notifications@github.com> wrote:
 

 @dhowe I gave you the whole repo above. Take your time.—

**Comment by dhowe** [comment]
So I'm now at the point where I can generate parser files from an external script, then compile/run my visitor from within Visual Studio.

If someone can help getting the .g4 file running from inside VS, that would be great
