### ISSUE TITLE
Antlr4cs generates parser files without any change in grammar file

### ISSUE THREAD

**Issue by JakubLinhart** [tunnelvisionlabs/antlr4cs#289]
**Steps to reproduce from Visual Studio:**
1. Open a g4 file in a project and do any change, save the g4 file.
2. Build the project from Visual Studio -> Antrl4Compile target generates *Lexer.cs, *Parser.cs, *Listener.cs, etc. files. This is OK and expected.
3. Add a new cs file to the project (no change in g4 file).
4. Build the project from Visual Studio again -> `Antlr4Compile` target runs unnecessary again.

**Steps to reproduce from command line:**
1. Build a project from command line using msbuild.
2. Antrl4Compile target generates *Lexer.cs, *Parser.cs, *Listener.cs, etc. files.
3. Don't do any changes and run msbuild again -> `Antlr4Compile` target runs unnecessary again.

Tested with Antlr4.CodeGenerator 4.6.4 and VS 15.7.1. I don't edit g4 files from Visual Studio.

It seems that `Antlr4DesignTimeBuild` msbuild property is in both cases `true` and msbuild omits `WriteLinesToFile` task to `Antlr4GenCodeFileNames` file which is output of `Antlr4Compile` target which explains the unnecessary rebuilds.

[Here](https://github.com/tunnelvisionlabs/antlr4cs/blame/master/runtime/CSharp/Antlr4BuildTasks/Antlr4.CodeGenerator.targets#L153) is the related change in `Antlr4.CodeGenerator.targets`.

An example project can be found [here](https://github.com/JakubLinhart/SphereSharp/tree/master/src/SphereSharp).

**Comment by sharwell** [comment]
This was introduced in 5e40358823eb5a9115260b82c90bd5a41f6ea8d2 and fixed in bcad85aef14d1df6b0a4fefe6ee67fc4adbeb109 for the 4.6.5-beta001 release.
