### ISSUE TITLE
Error using CSharpGenerator

### ISSUE THREAD

**Issue by FVillaf** [tunnelvisionlabs/antlr4cs#293]
When using the beta csharp generator with 
`
<PropertyGroup>
    <Antlr4UseCSharpGenerato>True<Antlr4UseCSharpGenerator>
</PropertyGroup>
`

the generated files can only grow. If the files must be shrink, they appear with garbage at the end (from the previous content, apparently). It is like the file is not deleted before regenerated, else simply refilled. The only workaround I found was to delete the garbage at end, at hand.

**Comment by sharwell** [comment]
:memo: I'll have this fix in a release soon. In the meantime, a rebuild operation will correct the problem if it occurs.

**Comment by sharwell** [comment]
@FVillaf Thanks so much for trying this out and reporting the issue. I just pushed 4.6.5-rc002 which corrects the issue.

**Comment by FVillaf** [comment]
Thanks Sam, very good work!
