### ISSUE TITLE
Build errors when upgrading from 4.6.5-rc002 to 4.6.5

### ISSUE THREAD

**Issue by rooks** [tunnelvisionlabs/antlr4cs#305]
I'm currently using `4.6.5-rc002` version. Everything is working fine. Her is my simple project:
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <Antlr4UseCSharpGenerator>True</Antlr4UseCSharpGenerator>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Antlr4" Version="4.6.5-rc002" />
  </ItemGroup>
  <ItemGroup>
    <Antlr4 Include="**/*.g4">
      <CustomToolNamespace>$(RootNamespace).Generated</CustomToolNamespace>
      <Listener>False</Listener>
      <Visitor>True</Visitor>
    </Antlr4>
  </ItemGroup>
</Project>
```

However when I'm trying to upgrade to latest stable `4.6.5` I'm getting a lot of build errors that could be divided in 2 categories.

1.  a lot of `Error	CS0246	The type or namespace name 'Antlr4' could not be found (are you missing a using directive or an assembly reference?)`

2. "duplicate items" error `MSB3105	The item "{generated_lexer_file}" was specified more than once in the "Sources" parameter.  Duplicate items are not supported by the "Sources" parameter.`

Am I missing something here? Do I need to adjust project for `4.6.5`?

--
Visual Studio version: 15.8.4

**Comment by sharwell** [comment]
Rather than use `<Antlr4 Include="...">`, you'll want to use `<Antlr4 Update="...">`. These files are now processed by default (similar to how .cs files are processed without including them explicitly), so you don't have to include them anymore. You only need the `Update` lines if you are making changes to the default metadata values (which you are - you're using a modified namespace, etc.).

As an alternative, you can disable the feature and specify the grammars explicitly by setting the following property:

```xml
<PropertyGroup>
  <EnableDefaultAntlrItems>False</EnableDefaultAntlrItems>
</PropertyGroup>
```

**Comment by rooks** [comment]
I've tried both options before actually and still got errors. Now I've checked it again and it seems that "duplicate items" errors are gone but "Antlr4 namespace" errors are still there for both options (`Update` or `EnableDefaultAntlrItems`). To fix it I need to manually reference transitive `Antlr4.Runtime` package.

Here is updated project that works:
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <Antlr4UseCSharpGenerator>True</Antlr4UseCSharpGenerator>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Antlr4" Version="4.6.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Antlr4.Runtime" Version="4.6.5" />
  </ItemGroup>
  <ItemGroup>
    <Antlr4 Update="**/*.g4">
      <CustomToolNamespace>$(RootNamespace).Generated</CustomToolNamespace>
      <Listener>False</Listener>
      <Visitor>True</Visitor>
    </Antlr4>
  </ItemGroup>
</Project>
```

**Comment by sharwell** [comment]
> To fix it I need to manually reference transitive Antlr4.Runtime package.

I'm guessing this was a transient problem. I just verified that the transitive reference is correctly defined in the Antlr4 package, so it was probably a case where NuGet messed up the local restore operation, and adding the new package reference caused it to retry.
