### ISSUE TITLE
Install CodeGenerator 4.6.5

### ISSUE THREAD

**Issue by maxime645** [tunnelvisionlabs/antlr4cs#306]
I am trying to upgrade the Antlr version I am working with in my project. Upgrade is successfull till version 4.6.4.
When I try to install 4.6.5 or one of the beta or rc version, the installation is always rolling back with error message 

> Microsoft.Build.Exceptions.InvalidProjectFileException: The attribute "Remove" in element <None> is unrecognized.  (...)\Projects\ConsoleApplication1\packages\Antlr4.CodeGenerator.4.6.5\build\Antlr4.CodeGenerator.props". 

I haven't found any documentation on this message when installing a Nuget Package.
I first thought about a project problem so I tried on a simple "Hello World" console application, but I have the same problem. I am working with VS2015 and .NET 4.5.
Do you have any clue on how I could have this fixed ?

**Comment by chrisc89** [comment]
I'm having the same problem with trying to install 4.6.5 in VS 2015 and .NET 4.6.1. I can install it via 2017 but still get this as a build error in VS 2015, which some developers on my project are using still.

**Comment by sharwell** [comment]
Thanks, I'll try to get this fixed this weekend.

**Comment by sharwell** [comment]
@maxime645 Can you try 4.6.6-rc001 and let me know if the problem is resolved? Once I get some additional validation I can push the 4.6.6 stable update.

**Comment by maxime645** [comment]
The release did solve my problem, thank you.

**Comment by chrisc89** [comment]
Thanks, i can confirm this has solved it for me also.
