### ISSUE TITLE
ERROR AC100 encountered, Visual Studio 2017 

### ISSUE THREAD

**Issue by awbushnell** [tunnelvisionlabs/antlr4cs#311]
Hello, we are using version 4.6.6-rc001 and one of our developers is encountering the following error both command line and in the IDE:

packages\Antlr4.CodeGenerator.4.6.6-rc001\build\Antlr4.CodeGenerator.targets(132,5): error
AC1000: Unknown build error: The system cannot find the file specified [CSProjectDir\OurProject.csproj]

However, the csproj referred to does exist where the error message is stating????

**Comment by sharwell** [comment]
It sounds like a problem launching Java. I would recommend trying again with the following property set in your project file:

```xml
<PropertyGroup>
  <Antlr4UseCSharpGenerator>True</Antlr4UseCSharpGenerator>
</PropertyGroup>
```

**Comment by awbushnell** [comment]
@sharwell That property was set.  The issue seemed user specific and a machine reboot seemed to help the issue, so not sure what was going on. I will just close this and thanks for the information will keep an eye open and if it should appear again, will try and get more diagnostics for a new issue..
