### ISSUE TITLE
Build failed for missing reference in Visual Studio 2017 

### ISSUE THREAD

**Issue by boydc2014** [tunnelvisionlabs/antlr4cs#312]
I'm following the instructions all the way down:

Install java
Install ANTLR language support
Install nuget package (Antlr4 4.6.6-rc001, only this one)
Create new item => combied grammer 

Then build failed, plenty of errors (85) for missing references: 

> CS0246	The type or namespace name 'Antlr4' could not be found (are you missing a using directive or an assembly reference?)	

Those errors come from the generated files in obj folder, so I think the generation process is good, looks sth is wrong with build process, but my csproj looks good to me:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Antlr4" Version="4.6.6-rc001">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
```
The project explorer looks like 
![image](https://user-images.githubusercontent.com/3829387/47552417-3f1b9100-d937-11e8-83a9-db74e927c4fe.png)

I don't know why the generation succeed but build failed, any ideas?

**Comment by boydc2014** [comment]
Update: manually add the dll reference solve that, the project file now looks like this 
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Antlr4" Version="4.6.6-rc001">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Antlr4.Runtime">
      <HintPath>..\..\..\..\..\.nuget\packages\antlr4.runtime\4.6.6-rc001\lib\netstandard1.1\Antlr4.Runtime.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
```
not looks good, any suggestions？

**Comment by lextm** [comment]
Please delete your manual reference to `Antlr4.Runtime` and add a package reference to `Antlr4.Runtime` instead.

**Comment by sharwell** [comment]
💭 I'm actually not sure how meta-packages are supposed to be published these days so they are correctly propagated to packages. Here's what I know works:

```xml
<PackageReference Include="Antlr4.Runtime" Version="4.6.6-rc001" />
<PackageReference Include="Antlr4.CodeGenerator" Version="4.6.6-rc001" PrivateAssets="all" />
```

**Comment by boydc2014** [comment]
Thanks @lextm @sharwell, how about we change the help document in ReadMe, so we teach people install those two, instead of the original one?

**Comment by lextm** [comment]
@boydc2014 4.6.6 is still a RC release. I assume @sharwell will update the documentation once it is made an official release.
