### ISSUE TITLE
Code generation ignores Directory.Build.props

### ISSUE THREAD

**Issue by mwpowellhtx** [tunnelvisionlabs/antlr4cs#322]
Mistakenly attributed to [Antlr4](/antlr/antlr4/issues/2518) project. Yes, probably correct, it belongs here.

I sometimes define my ``RootNamespace``, for instance, in a solution level ``Directory.Build.props``. However, when I do this, code generated by *Antlr4* lands in a *project* namespace ignoring this property. Suspect that the project file *itself* is being digested instead of using Visual Studio engine project properties.

Workaround is to add ``RootNamespace`` at the project level. It's a minor issue, but I should be able to relay that via the ``.props`` avenue.

**Comment by mwpowellhtx** [comment]
@sharwell I sent a sample project to you privately.

**Comment by mwpowellhtx** [comment]
@sharwell That did not fix it. I tried unloading the solution and reloading, still did not fix it.

Ah, I see, thanks. So, basically, this:

```xml
<ItemGroup>
  <Antlr4 Update="CaseRegression.g4"/>
</ItemGroup>
```

**Comment by sharwell** [comment]
thanks i'll check it out and get back to you

**Comment by mwpowellhtx** [comment]
@sharwell Remove the ``<RootNamespace>Kingdom.Protobuf</RootNamespace>`` and the other elements from the ``Kingdom.Protobuf.Antlr.csproj`` project and retry.

**Comment by mwpowellhtx** [comment]
@sharwell You can specify build properties at the solution level.

**Comment by mwpowellhtx** [comment]
@sharwell Ah I see... With a little help in my build properties to chain them, then it works.

```Xml
  <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))" />
```
