### ISSUE TITLE
Which Antlr version does this depend upon

### ISSUE THREAD

**Issue by mwpowellhtx** [tunnelvisionlabs/antlr4cs#325]
In particular, I think *ANTLR 4.2+* is beneficial to consider. Cheers, thank you!

**Comment by sharwell** [comment]
This project does not have external dependencies.

**Comment by mwpowellhtx** [comment]
@sharwell Am I wrong, *ANTLR4CS* does not exist in a vacuum apart from *ANTLR4*, does it? Which version is it based on? Do you track with the "parent" repository (loosely termed)?

**Comment by sharwell** [comment]
The repository tracks [tunnelvisionlabs/antlr4](https://github.com/tunnelvisionlabs/antlr4) for major.minor version.

**Comment by mwpowellhtx** [comment]
Thanks.
