### ISSUE TITLE
Power Query (M Language) Grammar

### ISSUE THREAD

**Issue by sjahongir** [tunnelvisionlabs/antlr4cs#326]
Can you provide a grammar for MS Power Query (M Language)?

**Comment by lextm** [comment]
This is a repo solely for the ANTLR C# runtime, so I don't think grammar design should be discussed here.

Usually people study existing samples on GitHub https://github.com/antlr/grammars-v4 and then design their own grammar files for different languages. (Well, you already opened an issue there https://github.com/antlr/grammars-v4/issues/1399)

**Comment by sharwell** [comment]
Sorry, I do not have such a grammar currently.
