### ISSUE TITLE
Is there any way to remove MyNamespace.program.cs file in generated files 

### ISSUE THREAD

**Issue by VictorCoder123** [tunnelvisionlabs/antlr4cs#327]
I followed the tutorial and generated all files in the intermediate output folder but I don't want to generate MyNamespace.program.cs file as a project cannot have two entry points. Is there anyway to remove it from generated files rather than manually delete it from build folder. 

A more general question: how to customize the parameters and options in the building process except choosing whether to generate visitor and listener? Should I just switch to Antlr4 command line tool to build the parser?

Thanks!
Victor

**Comment by sharwell** [comment]
> ... but I don't want to generate MyNamespace.program.cs file ...

This file is not being generated by this project. I would suggest asking this question in [dotnet/sdk](https://github.com/dotnet/sdk) instead.

> A more general question: how to customize the parameters and options in the building process except choosing whether to generate visitor and listener?

What are you trying to customize? You should see options in Visual Studio to configure various things via Solution Explorer.

> Should I just switch to Antlr4 command line tool to build the parser?

This runtime does not support command line code generation outside of the build process.

**Comment by VictorCoder123** [comment]
Thanks! Regarding the second question, I was wondering if I can customize the output folder for generated parser files and possibly include them in the source code instead of in the build folder.

**Comment by lextm** [comment]
@VictorCoder123 Please refer to existing threads like #160.

Overall, it is a bad idea (IMHO) to keep generated files in source folder and check into source code. Therefore, leaving them in the temp folder (like what WPF does) is the default behavior.
