### ISSUE TITLE
Label rules Enter method not called on listener.

### ISSUE THREAD

**Issue by fkpama** [tunnelvisionlabs/antlr4cs#329]
When creating a parser label rule and attaching a parser listener to the parser, the Enter/Exit methods are generated on the listener, the `Exit<Label>` method is correctly called on the listener, but the `Enter<Rulename>` is called instead of the `Enter<Label>` method.

#### MyParser.g4
```
rulename:
     alt1 # label1  
     | alt2 # label2
     ;
```
When entering label 1:

#### listener
```
class MyListener : MyParserListenerBase
{
    public override void EnterRulename(...) { } // <- This one is called on label1 enter
    public override void EnterLabel1(...) { }
    public override void ExitLabel1(...) { } // <- This one is called on label1 exit
}
```

**Comment by sharwell** [comment]
This is the expected behavior when using `addParseListener`. See also https://github.com/antlr/antlr4/issues/321#issuecomment-22737034.
