### ISSUE TITLE
suppressing warning messages

### ISSUE THREAD

**Issue by ipetrushevskiy** [tunnelvisionlabs/antlr4cs#337]
I have a warning message while building my lexer like:
'warning AC0146: non-fragment lexer rule '<some value>' can match the empty string'
I wanted to suppress it with 'ruleset' but I cant as its code 'AC0146' is not correctly passed somehow (looks like empty from VS error list window for example).
Is it any other way to do it?
Thanks in advance.

**Comment by KvanTTT** [comment]
Could you post a part of grammar with such a warning?

**Comment by ipetrushevskiy** [comment]
lexer grammar TestExample;
fragment BlockValue: ~[:{}]*;
BLOCK_VALUE: BlockValue;

**Comment by KvanTTT** [comment]
Just replace star `*` with plus `+` to get rid of warnings:

```
lexer grammar TestExample;
fragment BlockValue: ~[:{}]+;
BLOCK_VALUE: BlockValue;
```

**Comment by sharwell** [comment]
@ipetrushevskiy That grammar can match an infinite number of `BLOCK_VALUE` tokens between any other tokens. The warning needs to be fixed or the grammar is ambiguous.

**Comment by ipetrushevskiy** [comment]
Thanks for clarifications.
