### ISSUE TITLE
StringTemplate for C#?

### ISSUE THREAD

**Issue by BrianCatlin** [tunnelvisionlabs/antlr4cs#341]
Do you have any plans to update the StringTemplate NuGet package for C#? The existing package is old and creaky and depends upon ANTLRv3

**Comment by sharwell** [comment]
I don't have any objection to updating the package. However, there are two things to keep in mind here:

1. The repository for the [StringTemplate4](https://www.nuget.org/packages/StringTemplate4) package is [antlr/antlrcs](https://github.com/antlr/antlrcs).
2. StringTemplate 4 uses ANTLR 3, and there are no current plans for this to ever change. The same is true for the Java releases.
