### ISSUE TITLE
Visual Studio crashes when using plsql grammar files

### ISSUE THREAD

**Issue by nikstuckenbrock** [tunnelvisionlabs/antlr4cs#342]
Hello there,

I'm trying to use the plsql grammar files I found [here](https://github.com/antlr/grammars-v4/tree/master/plsql). When I add the [PlSqlLexer.cs](https://github.com/antlr/grammars-v4/blob/master/plsql/PlSqlLexer.g4) to my project Visual Studio crahes and there is no way to open the project.
I added the [PlSqlBaseLexer.cs](https://github.com/antlr/grammars-v4/blob/master/plsql/CSharp/PlSqlBaseLexer.cs), [PlSqlBaseParser.cs](https://github.com/antlr/grammars-v4/blob/master/plsql/CSharp/PlSqlBaseParser.cs) and [CaseChangingFileStream.cs](https://github.com/antlr/antlr4/blob/master/doc/resources/CaseChangingCharStream.cs) before the grammar file.
I'm using Visual Studio 2015 and installed the following NuGet-Packages:
- Antlr4
- Antlr4.CodeGenerator
- Antlr4.Runtime

I'm not sure, but I suppose the following extract of the ActivityLog.xml from my Visual Studio refers to the error:
`Unexpected system error mode before loading package [Remote Control Service Package]`

I hope there is someone who can help me with this.
Thanks in advance.

**Comment by sharwell** [comment]
Can you report this using the steps in https://aka.ms/reportPerf, and include a link to the feedback it creates on developercommunity.microsoft.com here?

**Comment by ttasi** [comment]
Not the original poster, but I came across the same issue, albeit using different version of VS. Created a report:

https://developercommunity.visualstudio.com/content/problem/971726/visual-studio-2017-high-memory-consumption-and-aut.html

The referenced attachment to reproduce the issue:
[plsqltest.zip](https://github.com/tunnelvisionlabs/antlr4cs/files/4412436/plsqltest.zip)

**Comment by KvanTTT** [comment]
I think this is linked with the size of the generated parsers. We are optimizing PL/SQL grammar, you can take a look at the intermediate result in our fork (not final): https://github.com/PositiveTechnologies/grammars-v4/tree/dev/plsql 

Also, I don't have any problems with the attached files (I have around 16 Gb RAM).
