### ISSUE TITLE
Make generated code more C#-ish

### ISSUE THREAD

**Issue by miloszkukla** [tunnelvisionlabs/antlr4cs#344]
I'm wondering whether generated code could more C#-ish, particularly I mean:
1) Opening { in a new line
2) Public field and method names starting from big letter
3) In *Parser class token types could be enum instead of consts
4)

In *Context classes like:

```
public partial class BarContext : ParserRuleContext {

		public IList<FooContext> _foos = new List<FooContext>();

		public FooContext[] foo() {
			return GetRuleContexts<FooContext>();
		} 
```

it's not clear what is the difference between _foos and foo() - maybe both could replaced with lazy-initialised property?

I guess point 1, 2 (and 3?) could be easily changed in \tool\resources\org\antlr\v4\tool\templates\codegen\CSharp\CSharp.stg

Since point 2, 3, 4 points would be breaking changes it could be switchable by an option.

**Comment by sharwell** [comment]
> Opening { in a new line

The current style was intentionally used to reduce file size when the generated code is very large. It's also the same reason hard tabs are used.

> Public field and method names starting from big letter

This is an unfortunate side effect of me not reviewing this closely enough in the early days of this target. At this point it would be a breaking change to switch, which I try to avoid unless absolutely necessary.

It's true that an option could avoid the breaking change, but each option also adds a bunch of testing complexity.

> In *Parser class token types could be enum instead of consts

This is similar to the previous.

> it's not clear what is the difference between _foo and foo()

Can you include the `bar` rule for reference?

**Comment by miloszkukla** [comment]
Oh, I see. Here is the grammar:

StringToken: 'A'..'Z';
foo: StringToken;
bar: 'Bar'
(
	foos += foo
)*;

**Comment by sharwell** [comment]
In most cases, I would recommend using this form:

```antlr
bar
  : 'Bar' foo*
  ;
```

This allows the use of `foo()` exclusively, and the confusion is avoided. Normally, if I need to use a label to disambiguate, then the label is sufficiently unique that I don't run the risk of confusing the names. For example, the following rule uses `enclosing`, `name`, `alias`, and `target` as labels ([source](https://github.com/tunnelvisionlabs/antlrworks2/blob/1e357ffbbac18cc0ca656e3c80e1e1e68f6e889d/org-antlr-works-editor/src/org/antlr/works/editor/st4/experimental/TemplateParser.g4#L59-L70)):

```
templateDef
    :   (   '@' enclosing=(ID|TRUE|FALSE) '.' name=(ID|TRUE|FALSE) '(' ')'
        |   name=(ID|TRUE|FALSE) '(' formalArgs ')'
        )
        '::='
        (   stringTemplate
        |   bigstringTemplate
        |   bigstringTemplateNoNewline
        )
    |   alias=(ID|TRUE|FALSE) '::=' target=(ID|TRUE|FALSE)
    ;
```

**Comment by miloszkukla** [comment]
Thank you a lot for answering :)
