### ISSUE TITLE
IntelliSense doesn't work with NetCore but works with Net Framework projects

### ISSUE THREAD

**Issue by KvanTTT** [tunnelvisionlabs/antlr4cs#345]
When I use generated lexer or parser. Classes are not being resolved at all, but the code is being compiled successfully.

**Comment by sharwell** [comment]
Can you provide a sample project which shows this?

**Comment by KvanTTT** [comment]
Sure. There is the .csproj file:

```xml
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net472</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Antlr4" Version="4.6.6" />
    </ItemGroup>

</Project>
```

Grammar file:

```g4
grammar G;

rule
    : A
    ;

A: [a-z]+;
```

And Program.cs:

```cs
using ConsoleApp2;

class Program
{
    static void Main(string[] args)
    {
        GParser gParser;
    }
}
```

If I switch `net472` to `netcoreapp2.1` the symbol `GParser` becomes unresolved:

![image](https://user-images.githubusercontent.com/1150330/78548878-2260d980-780a-11ea-843c-7e89960b06b3.png)

But compilation still works fine.

**Comment by KvanTTT** [comment]
It seems to me that this is the Rider bug because IntelliSense works fine in Visual Studio. I found a workaround for Rider: https://youtrack.jetbrains.com/issue/RIDER-37793#focus=streamItem-27-3905283.0-0
