### ISSUE TITLE
Resharper support

### ISSUE THREAD

**Issue by marhoily** [tunnelvisionlabs/antlr4cs#68]
You have already answered to this:

> ## If you have ReSharper installed, you should note that ReSharper does not support IntelliSense for 3rd-party code generation tools. You'll need to uninstall the extension or disable its IntelliSense customizations to restore the proper behavior, or bring the issue up with that company to find a solution. If you do not have ReSharper installed, please open a separate issue for this.

But there 2 issues:
a) be real. if I have to choose what saves more of my time antlr or resharper...
b) there's enormous amount of code-generating plug-ins. MS native: T4, XSD, setting files, winForms designer. And that is only what immediately comes to mind. And they all are supported by resharper. 

Actually it's quite obvious where you'd gone wrong. You should generate code into files that you include into project. That is it.

**Comment by krzkaczor** [comment]
In newest EAP version of ReSharper 9.2 there is extra option is project settings - Additional compile items. Just add there files that you need (parsers, visitors etc) and it works :) 

You can download EAP version from https://confluence.jetbrains.com/display/ReSharper/ReSharper+9.2+EAP
