### ISSUE TITLE
-Xforce-atn does not work

### ISSUE THREAD

**Issue by giessweinapps** [tunnelvisionlabs/antlr4cs#99]
Hi,

if i switch on the "Force ATN" option for my grammar, the build failed because the java executable getting passed the option "-force-atn" and this one is unexpected.

After a short lookup it seems that it is needed to pass "-Xforce-atn" to the ANTLR java executable. A little bugfix within the build Task is needed to fix this.

**Comment by sharwell** [comment]
Hi @giessweinapps,

Thank you for reporting this. I corrected the build task in ab7b0ae55800b615219f0d7f36acddbb0c483b8f, but it is not yet part of a release. To be honest, I didn't think anyone else was actually using this feature. :grinning:
